import type { CharacterSection } from '@/types/letters';

export const HIRAGANA_SECTIONS: CharacterSection[] = [
  {
    title: 'Dasar',
    description: 'Huruf vokal dan konsonan dasar',
    columns: 5,
    entries: [
      // a i u e o
      { char: 'あ', romaji: 'a', examples: [{ word: 'あさ', reading: 'asa', meaning: 'pagi' }] },
      { char: 'い', romaji: 'i', examples: [{ word: 'いぬ', reading: 'inu', meaning: 'anjing' }] },
      { char: 'う', romaji: 'u', examples: [{ word: 'うみ', reading: 'umi', meaning: 'laut' }] },
      { char: 'え', romaji: 'e', examples: [{ word: 'えき', reading: 'eki', meaning: 'stasiun' }] },
      { char: 'お', romaji: 'o', examples: [{ word: 'おか', reading: 'oka', meaning: 'bukit' }] },
      // ka ki ku ke ko
      { char: 'か', romaji: 'ka', examples: [{ word: 'かわ', reading: 'kawa', meaning: 'sungai' }] },
      { char: 'き', romaji: 'ki', examples: [{ word: 'きつね', reading: 'kitsune', meaning: 'rubah' }] },
      { char: 'く', romaji: 'ku', examples: [{ word: 'くも', reading: 'kumo', meaning: 'awan' }] },
      { char: 'け', romaji: 'ke', examples: [{ word: 'けむり', reading: 'kemuri', meaning: 'asap' }] },
      { char: 'こ', romaji: 'ko', examples: [{ word: 'こえ', reading: 'koe', meaning: 'suara' }] },
      // sa shi su se so
      { char: 'さ', romaji: 'sa', examples: [{ word: 'さくら', reading: 'sakura', meaning: 'bunga sakura' }] },
      { char: 'し', romaji: 'shi', examples: [{ word: 'しお', reading: 'shio', meaning: 'garam' }] },
      { char: 'す', romaji: 'su', examples: [{ word: 'すし', reading: 'sushi', meaning: 'sushi' }] },
      { char: 'せ', romaji: 'se', examples: [{ word: 'せかい', reading: 'sekai', meaning: 'dunia' }] },
      { char: 'そ', romaji: 'so', examples: [{ word: 'そら', reading: 'sora', meaning: 'langit' }] },
      // ta chi tsu te to
      { char: 'た', romaji: 'ta', examples: [{ word: 'たまご', reading: 'tamago', meaning: 'telur' }] },
      { char: 'ち', romaji: 'chi', examples: [{ word: 'ちず', reading: 'chizu', meaning: 'peta' }] },
      { char: 'つ', romaji: 'tsu', examples: [{ word: 'つき', reading: 'tsuki', meaning: 'bulan' }] },
      { char: 'て', romaji: 'te', examples: [{ word: 'てがみ', reading: 'tegami', meaning: 'surat' }] },
      { char: 'と', romaji: 'to', examples: [{ word: 'とり', reading: 'tori', meaning: 'burung' }] },
      // na ni nu ne no
      { char: 'な', romaji: 'na', examples: [{ word: 'なつ', reading: 'natsu', meaning: 'musim panas' }] },
      { char: 'に', romaji: 'ni', examples: [{ word: 'にほん', reading: 'nihon', meaning: 'Jepang' }] },
      { char: 'ぬ', romaji: 'nu', examples: [{ word: 'ぬの', reading: 'nuno', meaning: 'kain' }] },
      { char: 'ね', romaji: 'ne', examples: [{ word: 'ねこ', reading: 'neko', meaning: 'kucing' }] },
      { char: 'の', romaji: 'no', examples: [{ word: 'のり', reading: 'nori', meaning: 'rumput laut' }] },
      // ha hi fu he ho
      { char: 'は', romaji: 'ha', examples: [{ word: 'はな', reading: 'hana', meaning: 'bunga' }] },
      { char: 'ひ', romaji: 'hi', examples: [{ word: 'ひかり', reading: 'hikari', meaning: 'cahaya' }] },
      { char: 'ふ', romaji: 'fu', examples: [{ word: 'ふじ', reading: 'fuji', meaning: 'Gunung Fuji' }] },
      { char: 'へ', romaji: 'he', examples: [{ word: 'へや', reading: 'heya', meaning: 'kamar' }] },
      { char: 'ほ', romaji: 'ho', examples: [{ word: 'ほし', reading: 'hoshi', meaning: 'bintang' }] },
      // ma mi mu me mo
      { char: 'ま', romaji: 'ma', examples: [{ word: 'まち', reading: 'machi', meaning: 'kota' }] },
      { char: 'み', romaji: 'mi', examples: [{ word: 'みず', reading: 'mizu', meaning: 'air' }] },
      { char: 'む', romaji: 'mu', examples: [{ word: 'むし', reading: 'mushi', meaning: 'serangga' }] },
      { char: 'め', romaji: 'me', examples: [{ word: 'めだか', reading: 'medaka', meaning: 'ikan kecil' }] },
      { char: 'も', romaji: 'mo', examples: [{ word: 'もり', reading: 'mori', meaning: 'hutan' }] },
      // ya (gap) yu (gap) yo
      { char: 'や', romaji: 'ya', examples: [{ word: 'やま', reading: 'yama', meaning: 'gunung' }] },
      null,
      { char: 'ゆ', romaji: 'yu', examples: [{ word: 'ゆき', reading: 'yuki', meaning: 'salju' }] },
      null,
      { char: 'よ', romaji: 'yo', examples: [{ word: 'よる', reading: 'yoru', meaning: 'malam' }] },
      // ra ri ru re ro
      { char: 'ら', romaji: 'ra', examples: [{ word: 'らいねん', reading: 'rainen', meaning: 'tahun depan' }] },
      { char: 'り', romaji: 'ri', examples: [{ word: 'りんご', reading: 'ringo', meaning: 'apel' }] },
      { char: 'る', romaji: 'ru', examples: [{ word: 'るす', reading: 'rusu', meaning: 'tidak ada di rumah' }] },
      { char: 'れ', romaji: 're', examples: [{ word: 'れきし', reading: 'rekishi', meaning: 'sejarah' }] },
      { char: 'ろ', romaji: 'ro', examples: [{ word: 'ろうか', reading: 'rouka', meaning: 'koridor' }] },
      // wa (gap) (gap) (gap) wo
      { char: 'わ', romaji: 'wa', examples: [{ word: 'わたし', reading: 'watashi', meaning: 'saya' }] },
      null,
      null,
      null,
      { char: 'を', romaji: 'wo', examples: [{ word: 'をんな (古)', reading: 'wonna', meaning: 'perempuan (kuno)' }] },
      // n
      { char: 'ん', romaji: 'n', examples: [{ word: 'でんわ', reading: 'denwa', meaning: 'telepon' }] },
      null,
      null,
      null,
      null,
    ],
  },
  {
    title: 'Dakuon & Handakuon',
    description: 'Tambahkan simbol untuk mengubah bunyi',
    columns: 5,
    entries: [
      // ga gi gu ge go
      { char: 'が', romaji: 'ga', examples: [{ word: 'がっこう', reading: 'gakkou', meaning: 'sekolah' }] },
      { char: 'ぎ', romaji: 'gi', examples: [{ word: 'ぎんこう', reading: 'ginkou', meaning: 'bank' }] },
      { char: 'ぐ', romaji: 'gu', examples: [{ word: 'ぐあい', reading: 'guai', meaning: 'kondisi' }] },
      { char: 'げ', romaji: 'ge', examples: [{ word: 'げんき', reading: 'genki', meaning: 'sehat/semangat' }] },
      { char: 'ご', romaji: 'go', examples: [{ word: 'ごはん', reading: 'gohan', meaning: 'nasi/makan' }] },
      // za ji zu ze zo
      { char: 'ざ', romaji: 'za', examples: [{ word: 'ざっし', reading: 'zasshi', meaning: 'majalah' }] },
      { char: 'じ', romaji: 'ji', examples: [{ word: 'じかん', reading: 'jikan', meaning: 'waktu' }] },
      { char: 'ず', romaji: 'zu', examples: [{ word: 'ずかん', reading: 'zukan', meaning: 'buku bergambar' }] },
      { char: 'ぜ', romaji: 'ze', examples: [{ word: 'ぜんぶ', reading: 'zenbu', meaning: 'semua' }] },
      { char: 'ぞ', romaji: 'zo', examples: [{ word: 'ぞう', reading: 'zou', meaning: 'gajah' }] },
      // da ji zu de do
      { char: 'だ', romaji: 'da', examples: [{ word: 'だいがく', reading: 'daigaku', meaning: 'universitas' }] },
      { char: 'ぢ', romaji: 'ji', examples: [{ word: 'はなぢ', reading: 'hanaji', meaning: 'mimisan' }] },
      { char: 'づ', romaji: 'zu', examples: [{ word: 'つづく', reading: 'tsuzuku', meaning: 'berlanjut' }] },
      { char: 'で', romaji: 'de', examples: [{ word: 'でんしゃ', reading: 'densha', meaning: 'kereta' }] },
      { char: 'ど', romaji: 'do', examples: [{ word: 'どこ', reading: 'doko', meaning: 'di mana' }] },
      // ba bi bu be bo
      { char: 'ば', romaji: 'ba', examples: [{ word: 'ばら', reading: 'bara', meaning: 'mawar' }] },
      { char: 'び', romaji: 'bi', examples: [{ word: 'びょうき', reading: 'byouki', meaning: 'sakit' }] },
      { char: 'ぶ', romaji: 'bu', examples: [{ word: 'ぶた', reading: 'buta', meaning: 'babi' }] },
      { char: 'べ', romaji: 'be', examples: [{ word: 'べんきょう', reading: 'benkyou', meaning: 'belajar' }] },
      { char: 'ぼ', romaji: 'bo', examples: [{ word: 'ぼうし', reading: 'boushi', meaning: 'topi' }] },
      // pa pi pu pe po
      { char: 'ぱ', romaji: 'pa', examples: [{ word: 'ぱんだ', reading: 'panda', meaning: 'panda' }] },
      { char: 'ぴ', romaji: 'pi', examples: [{ word: 'ぴかぴか', reading: 'pikapika', meaning: 'berkilau' }] },
      { char: 'ぷ', romaji: 'pu', examples: [{ word: 'てんぷら', reading: 'tenpura', meaning: 'tempura' }] },
      { char: 'ぺ', romaji: 'pe', examples: [{ word: 'ぺん', reading: 'pen', meaning: 'pena' }] },
      { char: 'ぽ', romaji: 'po', examples: [{ word: 'さんぽ', reading: 'sanpo', meaning: 'jalan-jalan' }] },
    ],
  },
  {
    title: 'Combo',
    description: 'Tambahkan huruf kecil untuk membuat suku kata baru',
    columns: 3,
    entries: [
      { char: 'きゃ', romaji: 'kya', examples: [{ word: 'きゃく', reading: 'kyaku', meaning: 'tamu' }] },
      { char: 'きゅ', romaji: 'kyu', examples: [{ word: 'きゅう', reading: 'kyuu', meaning: 'sembilan' }] },
      { char: 'きょ', romaji: 'kyo', examples: [{ word: 'きょう', reading: 'kyou', meaning: 'hari ini' }] },
      { char: 'ぎゃ', romaji: 'gya', examples: [{ word: 'ぎゃく', reading: 'gyaku', meaning: 'kebalikan' }] },
      { char: 'ぎゅ', romaji: 'gyu', examples: [{ word: 'ぎゅうにゅう', reading: 'gyuunyuu', meaning: 'susu sapi' }] },
      { char: 'ぎょ', romaji: 'gyo', examples: [{ word: 'ぎょうざ', reading: 'gyouza', meaning: 'gyoza' }] },
      { char: 'しゃ', romaji: 'sha', examples: [{ word: 'しゃしん', reading: 'shashin', meaning: 'foto' }] },
      { char: 'しゅ', romaji: 'shu', examples: [{ word: 'しゅみ', reading: 'shumi', meaning: 'hobi' }] },
      { char: 'しょ', romaji: 'sho', examples: [{ word: 'しょくじ', reading: 'shokuji', meaning: 'makan' }] },
      { char: 'じゃ', romaji: 'ja', examples: [{ word: 'じゃあ', reading: 'jaa', meaning: 'kalau begitu' }] },
      { char: 'じゅ', romaji: 'ju', examples: [{ word: 'じゅぎょう', reading: 'jugyou', meaning: 'pelajaran' }] },
      { char: 'じょ', romaji: 'jo', examples: [{ word: 'じょうず', reading: 'jouzu', meaning: 'mahir' }] },
      { char: 'ちゃ', romaji: 'cha', examples: [{ word: 'おちゃ', reading: 'ocha', meaning: 'teh' }] },
      { char: 'ちゅ', romaji: 'chu', examples: [{ word: 'ちゅうごく', reading: 'chuugoku', meaning: 'China' }] },
      { char: 'ちょ', romaji: 'cho', examples: [{ word: 'ちょっと', reading: 'chotto', meaning: 'sebentar' }] },
      { char: 'にゃ', romaji: 'nya', examples: [{ word: 'にゃあ', reading: 'nyaa', meaning: 'suara kucing' }] },
      { char: 'にゅ', romaji: 'nyu', examples: [{ word: 'にゅうがく', reading: 'nyuugaku', meaning: 'masuk sekolah' }] },
      { char: 'にょ', romaji: 'nyo', examples: [{ word: 'にょろにょろ', reading: 'nyoronyoro', meaning: 'berkelok-kelok' }] },
      { char: 'ひゃ', romaji: 'hya', examples: [{ word: 'ひゃく', reading: 'hyaku', meaning: 'seratus' }] },
      { char: 'ひゅ', romaji: 'hyu', examples: [{ word: 'ひゅう', reading: 'hyuu', meaning: 'suara angin' }] },
      { char: 'ひょ', romaji: 'hyo', examples: [{ word: 'ひょう', reading: 'hyou', meaning: 'es batu' }] },
      { char: 'びゃ', romaji: 'bya', examples: [{ word: 'びゃく', reading: 'byaku', meaning: 'ratus (Sino)' }] },
      { char: 'びゅ', romaji: 'byu', examples: [{ word: 'びゅう', reading: 'byuu', meaning: 'suara angin keras' }] },
      { char: 'びょ', romaji: 'byo', examples: [{ word: 'びょういん', reading: 'byouin', meaning: 'rumah sakit' }] },
      { char: 'ぴゃ', romaji: 'pya', examples: [{ word: 'ぴゃあ', reading: 'pyaa', meaning: 'seruan kejutan' }] },
      { char: 'ぴゅ', romaji: 'pyu', examples: [{ word: 'ぴゅう', reading: 'pyuu', meaning: 'suara melengking' }] },
      { char: 'ぴょ', romaji: 'pyo', examples: [{ word: 'ぴょんぴょん', reading: 'pyonpyon', meaning: 'melompat-lompat' }] },
      { char: 'みゃ', romaji: 'mya', examples: [{ word: 'みゃく', reading: 'myaku', meaning: 'denyut nadi' }] },
      { char: 'みゅ', romaji: 'myu', examples: [{ word: 'みゅーじっく', reading: 'myuujikku', meaning: 'musik' }] },
      { char: 'みょ', romaji: 'myo', examples: [{ word: 'みょうじ', reading: 'myouji', meaning: 'nama keluarga' }] },
      { char: 'りゃ', romaji: 'rya', examples: [{ word: 'りゃくご', reading: 'ryakugo', meaning: 'singkatan' }] },
      { char: 'りゅ', romaji: 'ryu', examples: [{ word: 'りゅうがく', reading: 'ryuugaku', meaning: 'belajar di luar negeri' }] },
      { char: 'りょ', romaji: 'ryo', examples: [{ word: 'りょこう', reading: 'ryokou', meaning: 'perjalanan' }] },
    ],
  },
  {
    title: 'っ Kecil',
    description: 'Menggandakan konsonan berikutnya',
    columns: 4,
    entries: [
      { char: 'っ+k → kk', romaji: 'kk', examples: [{ word: 'きって', reading: 'kitte', meaning: 'perangko' }] },
      { char: 'っ+s → ss', romaji: 'ss', examples: [{ word: 'ざっし', reading: 'zasshi', meaning: 'majalah' }] },
      { char: 'っ+t → tt', romaji: 'tt', examples: [{ word: 'きっぷ', reading: 'kippu', meaning: 'tiket' }] },
      { char: 'っ+p → pp', romaji: 'pp', examples: [{ word: 'いっぱい', reading: 'ippai', meaning: 'penuh' }] },
    ],
  },
  {
    title: 'Vokal Panjang',
    description: 'Perpanjang bunyi vokal',
    columns: 5,
    entries: [
      { char: 'ああ', romaji: 'aa', examples: [{ word: 'おかあさん', reading: 'okaasan', meaning: 'ibu' }] },
      { char: 'いい', romaji: 'ii', examples: [{ word: 'おにいさん', reading: 'oniisan', meaning: 'kakak laki-laki' }] },
      { char: 'うう', romaji: 'uu', examples: [{ word: 'すうじ', reading: 'suuji', meaning: 'angka' }] },
      { char: 'ええ', romaji: 'ee', examples: [{ word: 'おねえさん', reading: 'oneesan', meaning: 'kakak perempuan' }] },
      { char: 'おお', romaji: 'oo', examples: [{ word: 'おおきい', reading: 'ookii', meaning: 'besar' }] },
      null,
      null,
      null,
      { char: 'えい', romaji: 'ei', examples: [{ word: 'えいご', reading: 'eigo', meaning: 'bahasa Inggris' }] },
      { char: 'おう', romaji: 'ou', examples: [{ word: 'おとうさん', reading: 'otousan', meaning: 'ayah' }] },
    ],
  },
];
