import type { CharacterSection } from '@/types/letters';

export const KATAKANA_SECTIONS: CharacterSection[] = [
  {
    title: 'Dasar',
    description: 'Huruf vokal dan konsonan dasar',
    columns: 5,
    entries: [
      // a i u e o
      { char: 'ア', romaji: 'a', examples: [{ word: 'アジア', reading: 'ajia', meaning: 'Asia' }] },
      { char: 'イ', romaji: 'i', examples: [{ word: 'イタリア', reading: 'itaria', meaning: 'Italia' }] },
      { char: 'ウ', romaji: 'u', examples: [{ word: 'ウイルス', reading: 'uirusu', meaning: 'virus' }] },
      { char: 'エ', romaji: 'e', examples: [{ word: 'エレベーター', reading: 'erebeetaa', meaning: 'lift' }] },
      { char: 'オ', romaji: 'o', examples: [{ word: 'オレンジ', reading: 'orenji', meaning: 'jeruk' }] },
      // ka ki ku ke ko
      { char: 'カ', romaji: 'ka', examples: [{ word: 'カメラ', reading: 'kamera', meaning: 'kamera' }] },
      { char: 'キ', romaji: 'ki', examples: [{ word: 'キロ', reading: 'kiro', meaning: 'kilo' }] },
      { char: 'ク', romaji: 'ku', examples: [{ word: 'クラス', reading: 'kurasu', meaning: 'kelas' }] },
      { char: 'ケ', romaji: 'ke', examples: [{ word: 'ケーキ', reading: 'keeki', meaning: 'kue' }] },
      { char: 'コ', romaji: 'ko', examples: [{ word: 'コーヒー', reading: 'koohii', meaning: 'kopi' }] },
      // sa shi su se so
      { char: 'サ', romaji: 'sa', examples: [{ word: 'サッカー', reading: 'sakkaa', meaning: 'sepak bola' }] },
      { char: 'シ', romaji: 'shi', examples: [{ word: 'シャツ', reading: 'shatsu', meaning: 'kemeja' }] },
      { char: 'ス', romaji: 'su', examples: [{ word: 'スポーツ', reading: 'supootsu', meaning: 'olahraga' }] },
      { char: 'セ', romaji: 'se', examples: [{ word: 'セーター', reading: 'seetaa', meaning: 'sweater' }] },
      { char: 'ソ', romaji: 'so', examples: [{ word: 'ソファ', reading: 'sofa', meaning: 'sofa' }] },
      // ta chi tsu te to
      { char: 'タ', romaji: 'ta', examples: [{ word: 'タクシー', reading: 'takushii', meaning: 'taksi' }] },
      { char: 'チ', romaji: 'chi', examples: [{ word: 'チョコレート', reading: 'chokoreeto', meaning: 'cokelat' }] },
      { char: 'ツ', romaji: 'tsu', examples: [{ word: 'ツアー', reading: 'tsuaa', meaning: 'tur' }] },
      { char: 'テ', romaji: 'te', examples: [{ word: 'テレビ', reading: 'terebi', meaning: 'televisi' }] },
      { char: 'ト', romaji: 'to', examples: [{ word: 'トマト', reading: 'tomato', meaning: 'tomat' }] },
      // na ni nu ne no
      { char: 'ナ', romaji: 'na', examples: [{ word: 'ナイフ', reading: 'naifu', meaning: 'pisau' }] },
      { char: 'ニ', romaji: 'ni', examples: [{ word: 'ニュース', reading: 'nyuusu', meaning: 'berita' }] },
      { char: 'ヌ', romaji: 'nu', examples: [{ word: 'ヌードル', reading: 'nuudoru', meaning: 'mi' }] },
      { char: 'ネ', romaji: 'ne', examples: [{ word: 'ネクタイ', reading: 'nekutai', meaning: 'dasi' }] },
      { char: 'ノ', romaji: 'no', examples: [{ word: 'ノート', reading: 'nooto', meaning: 'buku catatan' }] },
      // ha hi fu he ho
      { char: 'ハ', romaji: 'ha', examples: [{ word: 'ハム', reading: 'hamu', meaning: 'ham' }] },
      { char: 'ヒ', romaji: 'hi', examples: [{ word: 'ヒーター', reading: 'hiitaa', meaning: 'pemanas' }] },
      { char: 'フ', romaji: 'fu', examples: [{ word: 'フランス', reading: 'furansu', meaning: 'Prancis' }] },
      { char: 'ヘ', romaji: 'he', examples: [{ word: 'ヘルメット', reading: 'herumetto', meaning: 'helm' }] },
      { char: 'ホ', romaji: 'ho', examples: [{ word: 'ホテル', reading: 'hoteru', meaning: 'hotel' }] },
      // ma mi mu me mo
      { char: 'マ', romaji: 'ma', examples: [{ word: 'マップ', reading: 'mappu', meaning: 'peta' }] },
      { char: 'ミ', romaji: 'mi', examples: [{ word: 'ミルク', reading: 'miruku', meaning: 'susu' }] },
      { char: 'ム', romaji: 'mu', examples: [{ word: 'ムード', reading: 'muudo', meaning: 'suasana' }] },
      { char: 'メ', romaji: 'me', examples: [{ word: 'メール', reading: 'meeru', meaning: 'email' }] },
      { char: 'モ', romaji: 'mo', examples: [{ word: 'モデル', reading: 'moderu', meaning: 'model' }] },
      // ya (gap) yu (gap) yo
      { char: 'ヤ', romaji: 'ya', examples: [{ word: 'ヤシ', reading: 'yashi', meaning: 'kelapa' }] },
      null,
      { char: 'ユ', romaji: 'yu', examples: [{ word: 'ユニフォーム', reading: 'yunifoomu', meaning: 'seragam' }] },
      null,
      { char: 'ヨ', romaji: 'yo', examples: [{ word: 'ヨーグルト', reading: 'yooguruto', meaning: 'yogurt' }] },
      // ra ri ru re ro
      { char: 'ラ', romaji: 'ra', examples: [{ word: 'ラジオ', reading: 'rajio', meaning: 'radio' }] },
      { char: 'リ', romaji: 'ri', examples: [{ word: 'リモコン', reading: 'rimokon', meaning: 'remote control' }] },
      { char: 'ル', romaji: 'ru', examples: [{ word: 'ルール', reading: 'ruuru', meaning: 'aturan' }] },
      { char: 'レ', romaji: 're', examples: [{ word: 'レストラン', reading: 'resutoran', meaning: 'restoran' }] },
      { char: 'ロ', romaji: 'ro', examples: [{ word: 'ロボット', reading: 'robotto', meaning: 'robot' }] },
      // wa (gap) (gap) (gap) wo
      { char: 'ワ', romaji: 'wa', examples: [{ word: 'ワイン', reading: 'wain', meaning: 'anggur' }] },
      null,
      null,
      null,
      { char: 'ヲ', romaji: 'wo', examples: [{ word: 'ヲタク', reading: 'wotaku', meaning: 'otaku' }] },
      // n
      { char: 'ン', romaji: 'n', examples: [{ word: 'パン', reading: 'pan', meaning: 'roti' }] },
      null,
      null,
      null,
      null,
    ],
  },
  {
    title: 'Dakuon & Handakuon',
    description: 'Tambahkan simbol untuk mengubah bunyi',
    columns: 5,
    entries: [
      { char: 'ガ', romaji: 'ga', examples: [{ word: 'ガス', reading: 'gasu', meaning: 'gas' }] },
      { char: 'ギ', romaji: 'gi', examples: [{ word: 'ギター', reading: 'gitaa', meaning: 'gitar' }] },
      { char: 'グ', romaji: 'gu', examples: [{ word: 'グラス', reading: 'gurasu', meaning: 'gelas' }] },
      { char: 'ゲ', romaji: 'ge', examples: [{ word: 'ゲーム', reading: 'geemu', meaning: 'permainan' }] },
      { char: 'ゴ', romaji: 'go', examples: [{ word: 'ゴール', reading: 'gooru', meaning: 'gol' }] },
      { char: 'ザ', romaji: 'za', examples: [{ word: 'ザラザラ', reading: 'zarazara', meaning: 'kasar' }] },
      { char: 'ジ', romaji: 'ji', examples: [{ word: 'ジュース', reading: 'juusu', meaning: 'jus' }] },
      { char: 'ズ', romaji: 'zu', examples: [{ word: 'ズボン', reading: 'zubon', meaning: 'celana' }] },
      { char: 'ゼ', romaji: 'ze', examples: [{ word: 'ゼロ', reading: 'zero', meaning: 'nol' }] },
      { char: 'ゾ', romaji: 'zo', examples: [{ word: 'ゾーン', reading: 'zoon', meaning: 'zona' }] },
      { char: 'ダ', romaji: 'da', examples: [{ word: 'ダンス', reading: 'dansu', meaning: 'tarian' }] },
      { char: 'ヂ', romaji: 'ji', examples: [{ word: 'ヂスコ', reading: 'jisuko', meaning: 'disko (langka)' }] },
      { char: 'ヅ', romaji: 'zu', examples: [{ word: 'ヅカ', reading: 'zuka', meaning: 'Takarazuka (singkatan)' }] },
      { char: 'デ', romaji: 'de', examples: [{ word: 'デート', reading: 'deeto', meaning: 'kencan' }] },
      { char: 'ド', romaji: 'do', examples: [{ word: 'ドア', reading: 'doa', meaning: 'pintu' }] },
      { char: 'バ', romaji: 'ba', examples: [{ word: 'バス', reading: 'basu', meaning: 'bus' }] },
      { char: 'ビ', romaji: 'bi', examples: [{ word: 'ビール', reading: 'biiru', meaning: 'bir' }] },
      { char: 'ブ', romaji: 'bu', examples: [{ word: 'ブーツ', reading: 'buutsu', meaning: 'sepatu bot' }] },
      { char: 'ベ', romaji: 'be', examples: [{ word: 'ベッド', reading: 'beddo', meaning: 'tempat tidur' }] },
      { char: 'ボ', romaji: 'bo', examples: [{ word: 'ボール', reading: 'booru', meaning: 'bola' }] },
      { char: 'パ', romaji: 'pa', examples: [{ word: 'パスタ', reading: 'pasuta', meaning: 'pasta' }] },
      { char: 'ピ', romaji: 'pi', examples: [{ word: 'ピアノ', reading: 'piano', meaning: 'piano' }] },
      { char: 'プ', romaji: 'pu', examples: [{ word: 'プール', reading: 'puuru', meaning: 'kolam renang' }] },
      { char: 'ペ', romaji: 'pe', examples: [{ word: 'ペン', reading: 'pen', meaning: 'pena' }] },
      { char: 'ポ', romaji: 'po', examples: [{ word: 'ポスター', reading: 'posutaa', meaning: 'poster' }] },
    ],
  },
  {
    title: 'Combo',
    description: 'Tambahkan huruf kecil untuk membuat suku kata baru',
    columns: 3,
    entries: [
      { char: 'キャ', romaji: 'kya', examples: [{ word: 'キャンプ', reading: 'kyanpu', meaning: 'berkemah' }] },
      { char: 'キュ', romaji: 'kyu', examples: [{ word: 'キュウリ', reading: 'kyuuri', meaning: 'mentimun' }] },
      { char: 'キョ', romaji: 'kyo', examples: [{ word: 'キョウト', reading: 'kyouto', meaning: 'Kyoto' }] },
      { char: 'ギャ', romaji: 'gya', examples: [{ word: 'ギャップ', reading: 'gyappu', meaning: 'celah' }] },
      { char: 'ギュ', romaji: 'gyu', examples: [{ word: 'ギュウギュウ', reading: 'gyuugyuu', meaning: 'padat' }] },
      { char: 'ギョ', romaji: 'gyo', examples: [{ word: 'ギョウザ', reading: 'gyouza', meaning: 'gyoza' }] },
      { char: 'シャ', romaji: 'sha', examples: [{ word: 'シャワー', reading: 'shawaa', meaning: 'shower' }] },
      { char: 'シュ', romaji: 'shu', examples: [{ word: 'シュート', reading: 'shuuto', meaning: 'tendangan' }] },
      { char: 'ショ', romaji: 'sho', examples: [{ word: 'ショッピング', reading: 'shoppingu', meaning: 'belanja' }] },
      { char: 'ジャ', romaji: 'ja', examples: [{ word: 'ジャケット', reading: 'jaketto', meaning: 'jaket' }] },
      { char: 'ジュ', romaji: 'ju', examples: [{ word: 'ジュース', reading: 'juusu', meaning: 'jus' }] },
      { char: 'ジョ', romaji: 'jo', examples: [{ word: 'ジョギング', reading: 'jogingu', meaning: 'jogging' }] },
      { char: 'チャ', romaji: 'cha', examples: [{ word: 'チャンス', reading: 'chansu', meaning: 'kesempatan' }] },
      { char: 'チュ', romaji: 'chu', examples: [{ word: 'チューリップ', reading: 'chuurippu', meaning: 'tulip' }] },
      { char: 'チョ', romaji: 'cho', examples: [{ word: 'チョコレート', reading: 'chokoreeto', meaning: 'cokelat' }] },
      { char: 'ニャ', romaji: 'nya', examples: [{ word: 'ニャンコ', reading: 'nyanko', meaning: 'kucing (slang)' }] },
      { char: 'ニュ', romaji: 'nyu', examples: [{ word: 'ニュース', reading: 'nyuusu', meaning: 'berita' }] },
      { char: 'ニョ', romaji: 'nyo', examples: [{ word: 'ニョッキ', reading: 'nyokki', meaning: 'gnocchi' }] },
      { char: 'ヒャ', romaji: 'hya', examples: [{ word: 'ヒャク', reading: 'hyaku', meaning: 'seratus' }] },
      { char: 'ヒュ', romaji: 'hyu', examples: [{ word: 'ヒューズ', reading: 'hyuuzu', meaning: 'sekering' }] },
      { char: 'ヒョ', romaji: 'hyo', examples: [{ word: 'ヒョウ', reading: 'hyou', meaning: 'macan tutul' }] },
      { char: 'ビャ', romaji: 'bya', examples: [{ word: 'ビャクダン', reading: 'byakudan', meaning: 'cendana' }] },
      { char: 'ビュ', romaji: 'byu', examples: [{ word: 'ビュッフェ', reading: 'byuffe', meaning: 'prasmanan' }] },
      { char: 'ビョ', romaji: 'byo', examples: [{ word: 'ビョウイン', reading: 'byouin', meaning: 'rumah sakit' }] },
      { char: 'ピャ', romaji: 'pya', examples: [{ word: 'ピャ', reading: 'pya', meaning: 'seruan kejutan' }] },
      { char: 'ピュ', romaji: 'pyu', examples: [{ word: 'ピュア', reading: 'pyua', meaning: 'murni' }] },
      { char: 'ピョ', romaji: 'pyo', examples: [{ word: 'ピョンピョン', reading: 'pyonpyon', meaning: 'melompat-lompat' }] },
      { char: 'ミャ', romaji: 'mya', examples: [{ word: 'ミャンマー', reading: 'myanmaa', meaning: 'Myanmar' }] },
      { char: 'ミュ', romaji: 'myu', examples: [{ word: 'ミュージック', reading: 'myuujikku', meaning: 'musik' }] },
      { char: 'ミョ', romaji: 'myo', examples: [{ word: 'ミョウジ', reading: 'myouji', meaning: 'nama keluarga' }] },
      { char: 'リャ', romaji: 'rya', examples: [{ word: 'リャクゴ', reading: 'ryakugo', meaning: 'singkatan' }] },
      { char: 'リュ', romaji: 'ryu', examples: [{ word: 'リュック', reading: 'ryukku', meaning: 'ransel' }] },
      { char: 'リョ', romaji: 'ryo', examples: [{ word: 'リョコウ', reading: 'ryokou', meaning: 'perjalanan' }] },
    ],
  },
  {
    title: 'ッ Kecil',
    description: 'Menggandakan konsonan berikutnya',
    columns: 4,
    entries: [
      { char: 'ッ+k → kk', romaji: 'kk', examples: [{ word: 'バッグ', reading: 'baggu', meaning: 'tas' }] },
      { char: 'ッ+s → ss', romaji: 'ss', examples: [{ word: 'アッサリ', reading: 'assari', meaning: 'ringan/sederhana' }] },
      { char: 'ッ+t → tt', romaji: 'tt', examples: [{ word: 'ベッド', reading: 'beddo', meaning: 'tempat tidur' }] },
      { char: 'ッ+p → pp', romaji: 'pp', examples: [{ word: 'カップ', reading: 'kappu', meaning: 'cangkir' }] },
    ],
  },
  {
    title: 'Vokal Panjang',
    description: 'Perpanjang bunyi vokal dengan ー',
    columns: 5,
    entries: [
      { char: 'アー', romaji: 'aa', examples: [{ word: 'カード', reading: 'kaado', meaning: 'kartu' }] },
      { char: 'イー', romaji: 'ii', examples: [{ word: 'ティーム', reading: 'tiimu', meaning: 'tim' }] },
      { char: 'ウー', romaji: 'uu', examples: [{ word: 'プール', reading: 'puuru', meaning: 'kolam renang' }] },
      { char: 'エー', romaji: 'ee', examples: [{ word: 'ケーキ', reading: 'keeki', meaning: 'kue' }] },
      { char: 'オー', romaji: 'oo', examples: [{ word: 'コーヒー', reading: 'koohii', meaning: 'kopi' }] },
    ],
  },
];
