import type { QuizContent } from '@/types/quiz';

const quiz: QuizContent = {
  slug: 'kana-mastery',
  title: 'Kana Mastery Quiz',
  level: 'kana',
  category: 'vocab',
  questions: [
    {
      id: 'kana-1',
      questionText: '「あ」の読み方はどれですか。',
      options: [
        { id: 'a', text: 'a', isCorrect: true },
        { id: 'b', text: 'i', isCorrect: false },
        { id: 'c', text: 'u', isCorrect: false },
        { id: 'd', text: 'e', isCorrect: false },
      ],
      explanation: '「あ」は hiragana pertama dan dibaca "a". Ini adalah salah satu dari 5 huruf vokal dasar (あいうえお).',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-2',
      questionText: '「テレビ」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'TV', isCorrect: true },
        { id: 'b', text: 'Radio', isCorrect: false },
        { id: 'c', text: 'Buku', isCorrect: false },
        { id: 'd', text: 'Film', isCorrect: false },
      ],
      explanation: '「テレビ」(terebi) berasal dari bahasa Inggris "television" dan berarti "TV". Ditulis dalam katakana karena merupakan kata serapan asing.',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-3',
      questionText: '「ka」をひらがなで書くとどれですか。',
      options: [
        { id: 'a', text: 'か', isCorrect: true },
        { id: 'b', text: 'き', isCorrect: false },
        { id: 'c', text: 'く', isCorrect: false },
        { id: 'd', text: 'け', isCorrect: false },
      ],
      explanation: '「か」は "ka" と読みます。か行 (ka-ki-ku-ke-ko) は か・き・く・け・こ です。',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-4',
      questionText: '「ありがとう」の意味はどれですか。',
      options: [
        { id: 'a', text: 'Terima kasih', isCorrect: true },
        { id: 'b', text: 'Selamat pagi', isCorrect: false },
        { id: 'c', text: 'Permisi', isCorrect: false },
        { id: 'd', text: 'Maaf', isCorrect: false },
      ],
      explanation: '「ありがとう」(arigatou) berarti "terima kasih". Ini adalah salah satu ungkapan paling penting dalam bahasa Jepang.',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-5',
      questionText: '「が」はどの文字にだくてんを付けたものですか。',
      options: [
        { id: 'a', text: 'か', isCorrect: true },
        { id: 'b', text: 'さ', isCorrect: false },
        { id: 'c', text: 'た', isCorrect: false },
        { id: 'd', text: 'は', isCorrect: false },
      ],
      explanation: '「が」(ga) は「か」(ka) に濁点（゛）を付けたものです。Dakuten mengubah bunyi tak bersuara "ka" menjadi bersuara "ga".',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-6',
      questionText: '「コーヒー」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Kopi', isCorrect: true },
        { id: 'b', text: 'Teh', isCorrect: false },
        { id: 'c', text: 'Susu', isCorrect: false },
        { id: 'd', text: 'Jus', isCorrect: false },
      ],
      explanation: '「コーヒー」(koohii) berarti "kopi". Kata ini berasal dari bahasa Belanda "koffie" dan ditulis dalam katakana.',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-7',
      questionText: 'カタカナの「ア」はどう読みますか。',
      options: [
        { id: 'a', text: 'a', isCorrect: true },
        { id: 'b', text: 'ka', isCorrect: false },
        { id: 'c', text: 'sa', isCorrect: false },
        { id: 'd', text: 'ta', isCorrect: false },
      ],
      explanation: '「ア」はカタカナで "a" と読みます。ひらがなの「あ」と同じ音です。',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-8',
      questionText: '「みず」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Air', isCorrect: true },
        { id: 'b', text: 'Api', isCorrect: false },
        { id: 'c', text: 'Angin', isCorrect: false },
        { id: 'd', text: 'Tanah', isCorrect: false },
      ],
      explanation: '「みず」(mizu) berarti "air". Ditulis dalam hiragana karena merupakan kata asli Jepang. Dalam kanji ditulis 水。',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-9',
      questionText: '「きゃ」はどう読みますか。',
      options: [
        { id: 'a', text: 'kya', isCorrect: true },
        { id: 'b', text: 'kiya', isCorrect: false },
        { id: 'c', text: 'ka', isCorrect: false },
        { id: 'd', text: 'kyu', isCorrect: false },
      ],
      explanation: '「きゃ」は拗音（youon）で "kya" と読みます。「き」(ki) と小さい「ゃ」(ya) を組み合わせた一音節です。',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-10',
      questionText: '「おはよう」の意味はどれですか。',
      options: [
        { id: 'a', text: 'Selamat pagi', isCorrect: true },
        { id: 'b', text: 'Selamat malam', isCorrect: false },
        { id: 'c', text: 'Terima kasih', isCorrect: false },
        { id: 'd', text: 'Selamat tinggal', isCorrect: false },
      ],
      explanation: '「おはよう」(ohayou) berarti "selamat pagi". Bentuk sopannya adalah「おはようございます」(ohayou gozaimasu).',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-11',
      questionText: '「パン」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Roti', isCorrect: true },
        { id: 'b', text: 'Nasi', isCorrect: false },
        { id: 'c', text: 'Mie', isCorrect: false },
        { id: 'd', text: 'Kue', isCorrect: false },
      ],
      explanation: '「パン」(pan) berarti "roti". Kata ini berasal dari bahasa Portugis "pão" dan ditulis dalam katakana karena merupakan kata serapan.',
      category: 'vocab',
      level: 'kana',
    },
    {
      id: 'kana-12',
      questionText: 'カタカナの「ン」はどう読みますか。',
      options: [
        { id: 'a', text: 'n', isCorrect: true },
        { id: 'b', text: 'so', isCorrect: false },
        { id: 'c', text: 'shi', isCorrect: false },
        { id: 'd', text: 'tsu', isCorrect: false },
      ],
      explanation: '「ン」(n) はカタカナで唯一の子音単独文字です。「ソ」(so) と形が似ていますが、筆の方向が違います。ン は上から下、ソ は左から右に書きます。',
      category: 'vocab',
      level: 'kana',
    },
  ],
};

export default quiz;
