import type { QuizContent } from '@/types/quiz';

const quiz: QuizContent = {
  slug: 'n3-review',
  title: 'N3 Review Quiz',
  level: 'n3',
  category: 'grammar',
  questions: [
    {
      id: 'n3-1',
      questionText: '「問題」の読み方はどれですか。',
      options: [
        { id: 'a', text: 'もんだい', isCorrect: true },
        { id: 'b', text: 'もんたい', isCorrect: false },
        { id: 'c', text: 'とだい', isCorrect: false },
        { id: 'd', text: 'かんだい', isCorrect: false },
      ],
      explanation: '「問題」は「もんだい」(mondai) と読みます。意味は "masalah" atau "soal"。問 = tanya, 題 = topik/judul.',
      category: 'kanji',
      level: 'n3',
    },
    {
      id: 'n3-2',
      questionText: '「確認」の読み方はどれですか。',
      options: [
        { id: 'a', text: 'かくにん', isCorrect: true },
        { id: 'b', text: 'かくじん', isCorrect: false },
        { id: 'c', text: 'たしにん', isCorrect: false },
        { id: 'd', text: 'かくめい', isCorrect: false },
      ],
      explanation: '「確認」は「かくにん」(kakunin) と読みます。意味は "konfirmasi" atau "memastikan"。確 = pasti, 認 = mengakui.',
      category: 'kanji',
      level: 'n3',
    },
    {
      id: 'n3-3',
      questionText: '空がくもっている。雨が降る＿＿。',
      options: [
        { id: 'a', text: 'ようだ', isCorrect: true },
        { id: 'b', text: 'らしい', isCorrect: false },
        { id: 'c', text: 'そうだ（伝聞）', isCorrect: false },
        { id: 'd', text: 'みたいだ', isCorrect: false },
      ],
      explanation: '空を見て自分で判断しているので「〜ようだ」が正解です。〜ようだ digunakan saat dugaan berdasarkan pengamatan langsung sendiri. 〜らしい digunakan saat berdasarkan informasi dari orang lain.',
      category: 'grammar',
      level: 'n3',
    },
    {
      id: 'n3-4',
      questionText: 'ニュースによると、明日は雪が降る＿＿。',
      options: [
        { id: 'a', text: 'らしい', isCorrect: true },
        { id: 'b', text: 'ようだ', isCorrect: false },
        { id: 'c', text: 'はずだ', isCorrect: false },
        { id: 'd', text: 'つもりだ', isCorrect: false },
      ],
      explanation: '「ニュースによると」(menurut berita) menunjukkan informasi dari sumber lain, jadi menggunakan「〜らしい」。〜らしい digunakan untuk dugaan berdasarkan informasi yang didengar dari orang lain atau media.',
      category: 'grammar',
      level: 'n3',
    },
    {
      id: 'n3-5',
      questionText: '彼は10年も日本に住んでいるから、日本語が上手な＿＿。',
      options: [
        { id: 'a', text: 'はずだ', isCorrect: true },
        { id: 'b', text: 'ようだ', isCorrect: false },
        { id: 'c', text: 'らしい', isCorrect: false },
        { id: 'd', text: 'だろう', isCorrect: false },
      ],
      explanation: '「10年も住んでいるから」(karena sudah tinggal 10 tahun) menunjukkan keyakinan berdasarkan logika. 〜はずだ digunakan saat kita yakin sesuatu seharusnya benar berdasarkan alasan yang kuat.',
      category: 'grammar',
      level: 'n3',
    },
    {
      id: 'n3-6',
      questionText: '「先生に褒められた」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Dipuji oleh guru', isCorrect: true },
        { id: 'b', text: 'Memuji guru', isCorrect: false },
        { id: 'c', text: 'Guru ingin dipuji', isCorrect: false },
        { id: 'd', text: 'Menyuruh guru memuji', isCorrect: false },
      ],
      explanation: '「褒められた」は「褒める」(memuji) の受身形（bentuk pasif）です。先生に = oleh guru, 褒められた = dipuji. Jadi artinya "dipuji oleh guru".',
      category: 'grammar',
      level: 'n3',
    },
    {
      id: 'n3-7',
      questionText: '「母は弟に野菜を食べさせた」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Ibu menyuruh adik makan sayur', isCorrect: true },
        { id: 'b', text: 'Adik menyuruh ibu makan sayur', isCorrect: false },
        { id: 'c', text: 'Ibu memakan sayur adik', isCorrect: false },
        { id: 'd', text: 'Adik dipaksa makan sayur oleh ibu', isCorrect: false },
      ],
      explanation: '「食べさせた」は「食べる」の使役形（bentuk kausatif）です。母は (ibu sebagai subjek) + 弟に (adik sebagai orang yang disuruh) + 野菜を食べさせた (menyuruh makan sayur).',
      category: 'grammar',
      level: 'n3',
    },
    {
      id: 'n3-8',
      questionText: '「経験」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Pengalaman', isCorrect: true },
        { id: 'b', text: 'Pendapat', isCorrect: false },
        { id: 'c', text: 'Persiapan', isCorrect: false },
        { id: 'd', text: 'Penjelasan', isCorrect: false },
      ],
      explanation: '「経験」(keiken) berarti "pengalaman"。経 = melewati, 験 = menguji/mencoba. Jadi secara harfiah berarti "melewati dan menguji" — yaitu pengalaman.',
      category: 'vocab',
      level: 'n3',
    },
    {
      id: 'n3-9',
      questionText: '「準備」の読み方はどれですか。',
      options: [
        { id: 'a', text: 'じゅんび', isCorrect: true },
        { id: 'b', text: 'じゅんぴ', isCorrect: false },
        { id: 'c', text: 'しゅんび', isCorrect: false },
        { id: 'd', text: 'じゅんみ', isCorrect: false },
      ],
      explanation: '「準備」は「じゅんび」(junbi) と読みます。意味は "persiapan"。準 = standar/level, 備 = mempersiapkan.',
      category: 'kanji',
      level: 'n3',
    },
    {
      id: 'n3-10',
      questionText: '日本語が上手になる＿＿、毎日練習しています。',
      options: [
        { id: 'a', text: 'ように', isCorrect: true },
        { id: 'b', text: 'ために', isCorrect: false },
        { id: 'c', text: 'ので', isCorrect: false },
        { id: 'd', text: 'から', isCorrect: false },
      ],
      explanation: '「上手になる」(menjadi pandai) adalah kata kerja non-volitional (tidak bisa langsung dikontrol), jadi menggunakan「〜ように」。〜ために digunakan dengan kata kerja volitional yang bisa dikontrol langsung.',
      category: 'grammar',
      level: 'n3',
    },
    {
      id: 'n3-11',
      questionText: '次の文を読んでください。「調査によると、最近若者の読書量が減っている。しかし、電子書籍の利用は増えている。」この文の内容に合っているのはどれですか。',
      options: [
        { id: 'a', text: 'Anak muda membaca lebih sedikit buku, tapi penggunaan e-book meningkat', isCorrect: true },
        { id: 'b', text: 'Anak muda membaca lebih banyak buku dan e-book', isCorrect: false },
        { id: 'c', text: 'Penggunaan e-book dan buku cetak sama-sama menurun', isCorrect: false },
        { id: 'd', text: 'Survei menunjukkan anak muda tidak suka membaca', isCorrect: false },
      ],
      explanation: 'Teks menyatakan: 読書量が減っている (jumlah bacaan menurun) + しかし (namun) + 電子書籍の利用は増えている (penggunaan e-book meningkat). Kata kunci しかし menunjukkan kontras antara dua fakta.',
      category: 'reading',
      level: 'n3',
    },
    {
      id: 'n3-12',
      questionText: '「上司に残業させられた」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Terpaksa lembur oleh atasan', isCorrect: true },
        { id: 'b', text: 'Menyuruh atasan lembur', isCorrect: false },
        { id: 'c', text: 'Atasan lembur bersama saya', isCorrect: false },
        { id: 'd', text: 'Atasan meminta izin lembur', isCorrect: false },
      ],
      explanation: '「させられた」は使役受身形（bentuk kausatif-pasif）です。上司に = oleh atasan, 残業させられた = dipaksa lembur. Bentuk ini menunjukkan bahwa subjek TERPAKSA melakukan sesuatu — nuansanya negatif.',
      category: 'grammar',
      level: 'n3',
    },
  ],
};

export default quiz;
