import type { QuizContent } from '@/types/quiz';

const quiz: QuizContent = {
  slug: 'n4-review',
  title: 'N4 Review Quiz',
  level: 'n4',
  category: 'grammar',
  questions: [
    {
      id: 'n4-1',
      questionText: '「食べる」の漢字の読み方はどれですか。',
      options: [
        { id: 'a', text: 'たべる', isCorrect: true },
        { id: 'b', text: 'のべる', isCorrect: false },
        { id: 'c', text: 'しべる', isCorrect: false },
        { id: 'd', text: 'くべる', isCorrect: false },
      ],
      explanation: '「食べる」は「たべる」と読みます。「食」の kun-yomi は「た（べる）」で、「makan」という意味です。',
      category: 'kanji',
      level: 'n4',
    },
    {
      id: 'n4-2',
      questionText: '「書く」の可能形（bentuk potensial）はどれですか。',
      options: [
        { id: 'a', text: '書ける', isCorrect: true },
        { id: 'b', text: '書くれる', isCorrect: false },
        { id: 'c', text: '書かれる', isCorrect: false },
        { id: 'd', text: '書きれる', isCorrect: false },
      ],
      explanation: '「書く」は kelompok 1 — bentuk potensialnya: ganti akhiran -u ke -eru → 書ける (kakeru = bisa menulis). 書かれる adalah bentuk pasif, bukan potensial.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-3',
      questionText: '「宿題を＿＿から、遊びに行きます。」— Kata yang tepat untuk mengisi ＿＿ adalah?',
      options: [
        { id: 'a', text: 'してから', isCorrect: true },
        { id: 'b', text: 'するから', isCorrect: false },
        { id: 'c', text: 'したから', isCorrect: false },
        { id: 'd', text: 'しから', isCorrect: false },
      ],
      explanation: 'Pola 〜てから berarti "setelah melakukan ~". 宿題をしてから、遊びに行きます = setelah mengerjakan PR, pergi bermain. Bentuknya: te-form + から.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-4',
      questionText: '「雨が＿＿、試合は中止です。」— Bentuk kondisional yang paling tepat?',
      options: [
        { id: 'a', text: '降ったら', isCorrect: true },
        { id: 'b', text: '降るなら', isCorrect: false },
        { id: 'c', text: '降ると', isCorrect: false },
        { id: 'd', text: '降りば', isCorrect: false },
      ],
      explanation: '〜たら adalah kondisional yang paling serbaguna untuk situasi spesifik. 雨が降ったら = kalau hujan (nanti). 降りば salah karena bentuk ば dari 降る adalah 降れば.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-5',
      questionText: '「先生がお帰りに＿＿。」— Kata yang tepat untuk kalimat sonkeigo ini?',
      options: [
        { id: 'a', text: 'なりました', isCorrect: true },
        { id: 'b', text: 'しました', isCorrect: false },
        { id: 'c', text: 'いただきました', isCorrect: false },
        { id: 'd', text: 'まいりました', isCorrect: false },
      ],
      explanation: 'Pola sonkeigo: お〜になる digunakan untuk menghormati orang lain. 先生がお帰りになりました = guru sudah pulang (sopan). お〜しました dan いただきました adalah kenjougo (untuk diri sendiri).',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-6',
      questionText: '「電車」の読み方はどれですか。',
      options: [
        { id: 'a', text: 'でんしゃ', isCorrect: true },
        { id: 'b', text: 'でんくるま', isCorrect: false },
        { id: 'c', text: 'いなずまくるま', isCorrect: false },
        { id: 'd', text: 'でんち', isCorrect: false },
      ],
      explanation: '「電車」は「でんしゃ」と読みます。電 (den = listrik) + 車 (sha = kendaraan) = kereta listrik. Ini adalah jukugo yang menggunakan on-yomi.',
      category: 'kanji',
      level: 'n4',
    },
    {
      id: 'n4-7',
      questionText: '「ここで写真を撮って＿＿ですか。」— Kata yang tepat untuk meminta izin?',
      options: [
        { id: 'a', text: 'もいい', isCorrect: true },
        { id: 'b', text: 'もだめ', isCorrect: false },
        { id: 'c', text: 'はいけない', isCorrect: false },
        { id: 'd', text: 'ください', isCorrect: false },
      ],
      explanation: 'Pola 〜てもいいですか digunakan untuk meminta izin. 写真を撮ってもいいですか = bolehkah saya mengambil foto? 〜てはいけない berarti "tidak boleh" — kebalikannya.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-8',
      questionText: '「準備」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Persiapan', isCorrect: true },
        { id: 'b', text: 'Pengalaman', isCorrect: false },
        { id: 'c', text: 'Penjelasan', isCorrect: false },
        { id: 'd', text: 'Pelajaran', isCorrect: false },
      ],
      explanation: '「準備」(junbi) berarti "persiapan". Contoh penggunaan: 準備する (mempersiapkan), 準備ができた (persiapan sudah selesai). 経験 = pengalaman, 説明 = penjelasan, 授業 = pelajaran.',
      category: 'vocab',
      level: 'n4',
    },
    {
      id: 'n4-9',
      questionText: '「行く」の意志形（bentuk volitional）はどれですか。',
      options: [
        { id: 'a', text: '行こう', isCorrect: true },
        { id: 'b', text: '行きよう', isCorrect: false },
        { id: 'c', text: '行くよう', isCorrect: false },
        { id: 'd', text: '行けよう', isCorrect: false },
      ],
      explanation: '「行く」は kelompok 1 — bentuk volitional: ganti -u ke baris お + う → 行こう (ikou = ayo pergi). Untuk kelompok 2: ganti る→よう. Untuk する→しよう, くる→こよう.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-10',
      questionText: '「安＿＿、買います。」— Bentuk kondisional ～ば yang tepat untuk kata sifat「安い」?',
      options: [
        { id: 'a', text: 'ければ', isCorrect: true },
        { id: 'b', text: 'いれば', isCorrect: false },
        { id: 'c', text: 'くば', isCorrect: false },
        { id: 'd', text: 'ったら', isCorrect: false },
      ],
      explanation: 'Kata sifat -i → bentuk ば: ganti -i ke -kereba. 安い → 安ければ (yasukereba = kalau murah). 安かったら juga benar tapi itu bentuk 〜たら, bukan 〜ば.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-11',
      questionText: '「窓が開いている」はどういう意味ですか。',
      options: [
        { id: 'a', text: 'Jendela (sedang) terbuka', isCorrect: true },
        { id: 'b', text: 'Jendela sedang dibuka', isCorrect: false },
        { id: 'c', text: 'Jendela akan dibuka', isCorrect: false },
        { id: 'd', text: 'Jendela sudah ditutup', isCorrect: false },
      ],
      explanation: '「開いている」menggunakan pola 〜ている untuk menyatakan keadaan hasil. 窓が開いている = jendela dalam keadaan terbuka (bukan "sedang membuka"). 開く (aku) adalah kata kerja intransitif.',
      category: 'grammar',
      level: 'n4',
    },
    {
      id: 'n4-12',
      questionText: '「いただく」はどの jenis keigo ですか。',
      options: [
        { id: 'a', text: 'Kenjougo (謙譲語)', isCorrect: true },
        { id: 'b', text: 'Sonkeigo (尊敬語)', isCorrect: false },
        { id: 'c', text: 'Teineigo (丁寧語)', isCorrect: false },
        { id: 'd', text: 'Bukan keigo', isCorrect: false },
      ],
      explanation: '「いただく」adalah kenjougo (謙譲語) — bahasa merendahkan diri. Ini adalah bentuk rendah dari「もらう」(menerima). Digunakan ketika kamu menerima sesuatu dari orang yang dihormati. Contoh: 先生にいただきました = saya menerima dari guru.',
      category: 'grammar',
      level: 'n4',
    },
  ],
};

export default quiz;
