import type { TipCategory, TipDetail } from '@/types/letters';

export const HIRAGANA_TIP_CATEGORIES: TipCategory[] = [
  {
    label: 'HIRAGANA DASAR',
    items: [
      { slug: 'hiragana-vokal', characters: 'あ、い、う、え、お', romaji: 'a, i, u, e, o' },
      { slug: 'hiragana-k-group', characters: 'か、き、く、け、こ', romaji: 'ka, ki, ku, ke, ko' },
      { slug: 'hiragana-s-group', characters: 'さ、し、す、せ、そ', romaji: 'sa, shi, su, se, so' },
      { slug: 'hiragana-t-group', characters: 'た、ち、つ、て、と', romaji: 'ta, chi, tsu, te, to' },
      { slug: 'hiragana-n-group', characters: 'な、に、ぬ、ね、の', romaji: 'na, ni, nu, ne, no' },
      { slug: 'hiragana-h-group', characters: 'は、ひ、ふ、へ、ほ', romaji: 'ha, hi, fu, he, ho' },
      { slug: 'hiragana-m-group', characters: 'ま、み、む、め、も', romaji: 'ma, mi, mu, me, mo' },
      { slug: 'hiragana-y-group', characters: 'や、ゆ、よ', romaji: 'ya, yu, yo' },
      { slug: 'hiragana-r-group', characters: 'ら、り、る、れ、ろ', romaji: 'ra, ri, ru, re, ro' },
      { slug: 'hiragana-w-group', characters: 'わ、を、ん', romaji: 'wa, wo, n' },
    ],
  },
  {
    label: 'DAKUON & HANDAKUON',
    items: [
      { slug: 'hiragana-g-group', characters: 'が、ぎ、ぐ、げ、ご', romaji: 'ga, gi, gu, ge, go' },
      { slug: 'hiragana-z-group', characters: 'ざ、じ、ず、ぜ、ぞ', romaji: 'za, ji, zu, ze, zo' },
      { slug: 'hiragana-d-group', characters: 'だ、ぢ、づ、で、ど', romaji: 'da, ji, zu, de, do' },
      { slug: 'hiragana-b-group', characters: 'ば、び、ぶ、べ、ぼ', romaji: 'ba, bi, bu, be, bo' },
      { slug: 'hiragana-p-group', characters: 'ぱ、ぴ、ぷ、ぺ、ぽ', romaji: 'pa, pi, pu, pe, po' },
    ],
  },
  {
    label: 'KANA KECIL',
    items: [
      { slug: 'hiragana-ya-combo', characters: 'きゃ、みゃ、りゃ、にゃ、しゃ、ちゃ', romaji: 'kya, mya, rya, nya, sha, cha' },
      { slug: 'hiragana-yu-combo', characters: 'きゅ、みゅ、りゅ、ちゅ、にゅ、ひゅ、みゅ', romaji: 'kyu, myu, ryu, chu, nyu, hyu, myu' },
      { slug: 'hiragana-yo-combo', characters: 'きょ、にょ、ひょ、みょ、りょ、しょ、ちょ', romaji: 'kyo, nyo, hyo, myo, ryo, sho, cho' },
    ],
  },
  {
    label: 'EJAAN',
    items: [
      { slug: 'hiragana-small-tsu-1', characters: 'っ → kk, ss, tt', romaji: 'kk, ss, tt' },
      { slug: 'hiragana-long-vowels', characters: 'ああ、いい、うう、えい、おう', romaji: 'aa, ii, uu, ei, ou' },
    ],
  },
];

export const HIRAGANA_TIP_DETAILS: TipDetail[] = [
  {
    slug: 'hiragana-k-group',
    title: 'Hiragana: Kelompok K (か行)',
    explanation: 'Kelompok K terdiri dari lima suku kata yang semuanya menggunakan konsonan "k". Bunyi "k" dalam bahasa Jepang mirip dengan "k" dalam bahasa Indonesia, namun diucapkan tanpa hembusan udara berlebih.',
    cards: [
      { char: 'か', romaji: 'ka', englishComparison: 'seperti "ka" dalam "kamar"' },
      { char: 'き', romaji: 'ki', englishComparison: 'seperti "ki" dalam "kiri"' },
      { char: 'く', romaji: 'ku', englishComparison: 'seperti "ku" dalam "kuda"' },
      { char: 'け', romaji: 'ke', englishComparison: 'seperti "ke" dalam "keras"' },
      { char: 'こ', romaji: 'ko', englishComparison: 'seperti "ko" dalam "kota"' },
    ],
    closingText: 'Kelompok K adalah salah satu yang paling sering muncul dalam bahasa Jepang sehari-hari.',
  },
  {
    slug: 'hiragana-s-group',
    title: 'Hiragana: Kelompok S (さ行)',
    explanation: 'Kelompok S unik karena し (shi) tidak mengikuti pola biasa — bunyinya "shi", bukan "si". Ini adalah pengecualian penting yang perlu diingat.',
    cards: [
      { char: 'さ', romaji: 'sa', englishComparison: 'seperti "sa" dalam "sapu"' },
      { char: 'し', romaji: 'shi', englishComparison: 'seperti "shi" dalam "sheep" (bukan "si")' },
      { char: 'す', romaji: 'su', englishComparison: 'seperti "su" dalam "susu"' },
      { char: 'せ', romaji: 'se', englishComparison: 'seperti "se" dalam "sehat"' },
      { char: 'そ', romaji: 'so', englishComparison: 'seperti "so" dalam "soal"' },
    ],
    closingText: 'Ingat: し diucapkan "shi" — ini adalah pengecualian bunyi dalam kelompok S.',
  },
  {
    slug: 'hiragana-t-group',
    title: 'Hiragana: Kelompok T (た行)',
    explanation: 'Kelompok T memiliki dua pengecualian bunyi: ち diucapkan "chi" dan つ diucapkan "tsu". Keduanya berbeda dari pola konsonan T biasa.',
    cards: [
      { char: 'た', romaji: 'ta', englishComparison: 'seperti "ta" dalam "tahu"' },
      { char: 'ち', romaji: 'chi', englishComparison: 'seperti "chi" dalam "champion" (bukan "ti")' },
      { char: 'つ', romaji: 'tsu', englishComparison: 'seperti "tsu" — gabungan "t" dan "su"' },
      { char: 'て', romaji: 'te', englishComparison: 'seperti "te" dalam "teman"' },
      { char: 'と', romaji: 'to', englishComparison: 'seperti "to" dalam "tomat"' },
    ],
    closingText: 'ち = "chi" dan つ = "tsu" adalah dua pengecualian penting dalam kelompok T.',
  },
  {
    slug: 'hiragana-n-group',
    title: 'Hiragana: Kelompok N (な行)',
    explanation: 'Kelompok N menggunakan konsonan "n" yang lembut, mirip dengan "n" dalam bahasa Indonesia. Semua suku kata dalam kelompok ini mengikuti pola yang konsisten.',
    cards: [
      { char: 'な', romaji: 'na', englishComparison: 'seperti "na" dalam "nama"' },
      { char: 'に', romaji: 'ni', englishComparison: 'seperti "ni" dalam "nilai"' },
      { char: 'ぬ', romaji: 'nu', englishComparison: 'seperti "nu" dalam "nusa"' },
      { char: 'ね', romaji: 'ne', englishComparison: 'seperti "ne" dalam "nenek"' },
      { char: 'の', romaji: 'no', englishComparison: 'seperti "no" dalam "nona"' },
    ],
    closingText: 'Kelompok N sangat konsisten — semua mengikuti pola "n + vokal" tanpa pengecualian.',
  },
  {
    slug: 'hiragana-h-group',
    title: 'Hiragana: Kelompok H (は行)',
    explanation: 'Kelompok H memiliki satu pengecualian: ふ diucapkan "fu", bukan "hu". Bunyinya seperti udara yang keluar lembut dari bibir yang hampir tertutup.',
    cards: [
      { char: 'は', romaji: 'ha', englishComparison: 'seperti "ha" dalam "hari"' },
      { char: 'ひ', romaji: 'hi', englishComparison: 'seperti "hi" dalam "hina"' },
      { char: 'ふ', romaji: 'fu', englishComparison: 'seperti "fu" — hembusan udara lembut dari bibir' },
      { char: 'へ', romaji: 'he', englishComparison: 'seperti "he" dalam "heran"' },
      { char: 'ほ', romaji: 'ho', englishComparison: 'seperti "ho" dalam "hormat"' },
    ],
    closingText: 'ふ diucapkan "fu" bukan "hu" — bibir hampir tertutup saat mengucapkannya.',
  },
  {
    slug: 'hiragana-m-group',
    title: 'Hiragana: Kelompok M (ま行)',
    explanation: 'Kelompok M menggunakan konsonan "m" yang konsisten di semua suku kata. Bunyinya persis seperti "m" dalam bahasa Indonesia.',
    cards: [
      { char: 'ま', romaji: 'ma', englishComparison: 'seperti "ma" dalam "makan"' },
      { char: 'み', romaji: 'mi', englishComparison: 'seperti "mi" dalam "minum"' },
      { char: 'む', romaji: 'mu', englishComparison: 'seperti "mu" dalam "murah"' },
      { char: 'め', romaji: 'me', englishComparison: 'seperti "me" dalam "merah"' },
      { char: 'も', romaji: 'mo', englishComparison: 'seperti "mo" dalam "mobil"' },
    ],
    closingText: 'Kelompok M sangat mudah karena bunyinya sama persis dengan bahasa Indonesia.',
  },
  {
    slug: 'hiragana-y-group',
    title: 'Hiragana: Kelompok Y (や行)',
    explanation: 'Kelompok Y hanya memiliki tiga suku kata: や, ゆ, dan よ. Posisi い dan え sudah diisi oleh huruf vokal, sehingga kelompok ini tidak lengkap.',
    cards: [
      { char: 'や', romaji: 'ya', englishComparison: 'seperti "ya" dalam "yakin"' },
      { char: 'ゆ', romaji: 'yu', englishComparison: 'seperti "yu" dalam "yuk"' },
      { char: 'よ', romaji: 'yo', englishComparison: 'seperti "yo" dalam "yoga"' },
    ],
    closingText: 'Kelompok Y hanya tiga huruf — ya, yu, yo. Huruf-huruf ini juga digunakan dalam kombinasi suku kata.',
  },
  {
    slug: 'hiragana-r-group',
    title: 'Hiragana: Kelompok R (ら行)',
    explanation: 'Bunyi "r" dalam bahasa Jepang unik — bukan "r" bergetar seperti bahasa Indonesia, juga bukan "l" atau "r" bahasa Inggris. Lidah menyentuh langit-langit mulut sekali dengan cepat.',
    cards: [
      { char: 'ら', romaji: 'ra', englishComparison: 'seperti "ra" tapi dengan sentuhan lidah sekali ke langit-langit' },
      { char: 'り', romaji: 'ri', englishComparison: 'seperti "ri" dengan sentuhan lidah sekali' },
      { char: 'る', romaji: 'ru', englishComparison: 'seperti "ru" dengan sentuhan lidah sekali' },
      { char: 'れ', romaji: 're', englishComparison: 'seperti "re" dengan sentuhan lidah sekali' },
      { char: 'ろ', romaji: 'ro', englishComparison: 'seperti "ro" dengan sentuhan lidah sekali' },
    ],
    closingText: 'Bunyi "r" Jepang berada di antara "r" dan "l" — lidah menyentuh langit-langit mulut sekali saja.',
  },
  {
    slug: 'hiragana-w-group',
    title: 'Hiragana: Kelompok W & N (わ行 + ん)',
    explanation: 'Kelompok W hanya memiliki わ dan を. Huruf を hampir selalu digunakan sebagai partikel objek, bukan di awal kata. ん adalah satu-satunya konsonan yang berdiri sendiri tanpa vokal.',
    cards: [
      { char: 'わ', romaji: 'wa', englishComparison: 'seperti "wa" dalam "warna"' },
      { char: 'を', romaji: 'wo', englishComparison: 'diucapkan "o" — digunakan sebagai partikel objek' },
      { char: 'ん', romaji: 'n', englishComparison: 'seperti "n" di akhir kata — "den" dalam "denwa"' },
    ],
    closingText: 'を hampir selalu digunakan sebagai partikel (penanda objek kalimat), bukan sebagai bagian dari kata biasa.',
  },
  {
    slug: 'hiragana-g-group',
    title: 'Hiragana: Kelompok G (が行)',
    explanation: 'Kelompok G adalah versi bersuara dari kelompok K. Tambahkan dua titik kecil (dakuten ゛) di pojok kanan atas huruf K untuk mendapatkan huruf G.',
    cards: [
      { char: 'が', romaji: 'ga', englishComparison: 'seperti "ga" dalam "gajah"' },
      { char: 'ぎ', romaji: 'gi', englishComparison: 'seperti "gi" dalam "gigi"' },
      { char: 'ぐ', romaji: 'gu', englishComparison: 'seperti "gu" dalam "gunung"' },
      { char: 'げ', romaji: 'ge', englishComparison: 'seperti "ge" dalam "gelap"' },
      { char: 'ご', romaji: 'go', englishComparison: 'seperti "go" dalam "goreng"' },
    ],
    closingText: 'Dakuten (゛) mengubah K → G, S → Z, T → D, H → B. Pelajari pola ini dan kamu bisa membaca banyak huruf baru sekaligus.',
  },
  {
    slug: 'hiragana-z-group',
    title: 'Hiragana: Kelompok Z (ざ行)',
    explanation: 'Kelompok Z adalah versi bersuara dari kelompok S. Perhatikan: じ diucapkan "ji", bukan "zi" — sama seperti し yang diucapkan "shi".',
    cards: [
      { char: 'ざ', romaji: 'za', englishComparison: 'seperti "za" dalam "zaman"' },
      { char: 'じ', romaji: 'ji', englishComparison: 'seperti "ji" dalam "jika" (bukan "zi")' },
      { char: 'ず', romaji: 'zu', englishComparison: 'seperti "zu" dalam "zulu"' },
      { char: 'ぜ', romaji: 'ze', englishComparison: 'seperti "ze" dalam "zest"' },
      { char: 'ぞ', romaji: 'zo', englishComparison: 'seperti "zo" — bunyi Z dengan vokal "o"' },
    ],
    closingText: 'じ = "ji" adalah pengecualian, sama seperti し = "shi" di kelompok S.',
  },
  {
    slug: 'hiragana-d-group',
    title: 'Hiragana: Kelompok D (だ行)',
    explanation: 'Kelompok D adalah versi bersuara dari kelompok T. ぢ dan づ jarang digunakan dan bunyinya sama dengan じ dan ず — keduanya ada karena alasan historis.',
    cards: [
      { char: 'だ', romaji: 'da', englishComparison: 'seperti "da" dalam "daging"' },
      { char: 'ぢ', romaji: 'ji', englishComparison: 'diucapkan "ji" — sama bunyi dengan じ, jarang digunakan' },
      { char: 'づ', romaji: 'zu', englishComparison: 'diucapkan "zu" — sama bunyi dengan ず, jarang digunakan' },
      { char: 'で', romaji: 'de', englishComparison: 'seperti "de" dalam "dekat"' },
      { char: 'ど', romaji: 'do', englishComparison: 'seperti "do" dalam "dorong"' },
    ],
    closingText: 'ぢ dan づ muncul terutama dalam kata-kata majemuk. Dalam praktiknya, じ dan ず jauh lebih sering ditemui.',
  },
  {
    slug: 'hiragana-b-group',
    title: 'Hiragana: Kelompok B (ば行)',
    explanation: 'Kelompok B adalah versi bersuara dari kelompok H. Tambahkan dakuten (゛) di pojok kanan atas huruf H untuk mendapatkan huruf B.',
    cards: [
      { char: 'ば', romaji: 'ba', englishComparison: 'seperti "ba" dalam "baca"' },
      { char: 'び', romaji: 'bi', englishComparison: 'seperti "bi" dalam "biru"' },
      { char: 'ぶ', romaji: 'bu', englishComparison: 'seperti "bu" dalam "buku"' },
      { char: 'べ', romaji: 'be', englishComparison: 'seperti "be" dalam "benar"' },
      { char: 'ぼ', romaji: 'bo', englishComparison: 'seperti "bo" dalam "bola"' },
    ],
    closingText: 'Kelompok B berasal dari H + dakuten. Ingat polanya: は→ば、ひ→び、ふ→ぶ、へ→べ、ほ→ぼ.',
  },
  {
    slug: 'hiragana-p-group',
    title: 'Hiragana: Kelompok P (ぱ行)',
    explanation: 'Kelompok P adalah satu-satunya yang menggunakan handakuten — lingkaran kecil (゜) di pojok kanan atas huruf H. Ini adalah kelompok terakhir dalam sistem dakuon.',
    cards: [
      { char: 'ぱ', romaji: 'pa', englishComparison: 'seperti "pa" dalam "pagi"' },
      { char: 'ぴ', romaji: 'pi', englishComparison: 'seperti "pi" dalam "pikir"' },
      { char: 'ぷ', romaji: 'pu', englishComparison: 'seperti "pu" dalam "putar"' },
      { char: 'ぺ', romaji: 'pe', englishComparison: 'seperti "pe" dalam "pesan"' },
      { char: 'ぽ', romaji: 'po', englishComparison: 'seperti "po" dalam "potong"' },
    ],
    closingText: 'Handakuten (゜) hanya digunakan pada kelompok H untuk membentuk kelompok P. Lingkaran kecil ini membedakannya dari dakuten (゛).',
  },
  {
    slug: 'hiragana-yu-combo',
    title: 'Hiragana Combo (yu)',
    explanation: 'Sama seperti kombinasi ゃ, kamu bisa menambahkan ゅ kecil untuk mengubah bunyi huruf sebelumnya menjadi kombinasi dengan "yu". Ini membentuk satu suku kata.',
    cards: [
      { char: 'きゅ', romaji: 'kyu', englishComparison: 'seperti "kyu" — K + yu dalam satu suku kata' },
      { char: 'しゅ', romaji: 'shu', englishComparison: 'seperti "shu" dalam "shutter"' },
      { char: 'ちゅ', romaji: 'chu', englishComparison: 'seperti "chu" dalam "chute"' },
      { char: 'にゅ', romaji: 'nyu', englishComparison: 'seperti "nyu" — N + yu dalam satu suku kata' },
      { char: 'りゅ', romaji: 'ryu', englishComparison: 'seperti "ryu" — bunyi R + yu' },
    ],
    closingText: 'Ingat: ゅ harus kecil untuk membentuk kombinasi. ゅ besar (ゆ) adalah huruf sendiri yang dibaca "yu".',
  },
  {
    slug: 'hiragana-yo-combo',
    title: 'Hiragana Combo (yo)',
    explanation: 'Kombinasi dengan ょ kecil mengubah bunyi huruf sebelumnya menjadi gabungan dengan "yo". Seperti kombinasi ゃ dan ゅ, ini juga membentuk satu suku kata.',
    cards: [
      { char: 'きょ', romaji: 'kyo', englishComparison: 'seperti "kyo" — K + yo dalam satu suku kata' },
      { char: 'しょ', romaji: 'sho', englishComparison: 'seperti "sho" dalam "show"' },
      { char: 'ちょ', romaji: 'cho', englishComparison: 'seperti "cho" dalam "chop"' },
      { char: 'にょ', romaji: 'nyo', englishComparison: 'seperti "nyo" dalam "nyonya"' },
      { char: 'りょ', romaji: 'ryo', englishComparison: 'seperti "ryo" — R + yo dalam satu suku kata' },
    ],
    closingText: 'Dengan menguasai tiga set kombinasi (ゃ, ゅ, ょ), kamu menambah puluhan suku kata baru ke perbendaharaan hiragana-mu.',
  },
  {
    slug: 'hiragana-vokal',
    title: 'Hiragana: Huruf Vokal',
    explanation: 'Lima vokal dasar adalah fondasi dari seluruh sistem hiragana. Setiap suku kata dalam bahasa Jepang diakhiri dengan salah satu dari lima bunyi vokal ini.',
    cards: [
      { char: 'あ', romaji: 'a', englishComparison: 'seperti "a" dalam "ayah"' },
      { char: 'い', romaji: 'i', englishComparison: 'seperti "i" dalam "ikan"' },
      { char: 'う', romaji: 'u', englishComparison: 'seperti "u" dalam "ujung"' },
      { char: 'え', romaji: 'e', englishComparison: 'seperti "e" dalam "enak"' },
      { char: 'お', romaji: 'o', englishComparison: 'seperti "o" dalam "obat"' },
    ],
    closingText: 'Hafalkan lima vokal ini terlebih dahulu — semuanya digunakan bersama konsonan untuk membentuk suku kata lainnya.',
  },
  {
    slug: 'hiragana-ya-combo',
    title: 'Hiragana Combo (ya)',
    explanation: 'Kamu bisa menambahkan ゃ kecil untuk mengubah bunyi huruf sebelumnya. Ini membentuk satu suku kata — bukan dua!',
    cards: [
      { char: 'しゃ', romaji: 'sha', englishComparison: 'seperti "sha" dalam "share"' },
      { char: 'ちゃ', romaji: 'cha', englishComparison: 'seperti "cha" dalam "champion"' },
      { char: 'にゃ', romaji: 'nya', englishComparison: 'seperti "nya" dalam "nyata"' },
      { char: 'きゃ', romaji: 'kya', englishComparison: 'seperti "kya" dalam "kyak"' },
    ],
    closingText: 'Ingat: しゃ dengan ゃ kecil diucapkan "sha" (satu suku kata), berbeda dengan しや dengan ゃ besar yang diucapkan "shi-ya" (dua suku kata).',
  },
  {
    slug: 'hiragana-small-tsu-1',
    title: 'っ Kecil — Konsonan Ganda',
    explanation: 'っ kecil menggandakan konsonan yang mengikutinya. Ada jedaan singkat sebelum konsonan tersebut diucapkan.',
    cards: [
      { char: 'きって', romaji: 'kitte', englishComparison: 'perangko — perhatikan jeda sebelum "t"' },
      { char: 'ざっし', romaji: 'zasshi', englishComparison: 'majalah — perhatikan jeda sebelum "sh"' },
      { char: 'きっぷ', romaji: 'kippu', englishComparison: 'tiket — perhatikan jeda sebelum "p"' },
    ],
    closingText: 'Bayangkan seperti menahan napas sejenak sebelum mengucapkan konsonan ganda tersebut.',
  },
  {
    slug: 'hiragana-long-vowels',
    title: 'Vokal Panjang',
    explanation: 'Dalam hiragana, vokal panjang dibentuk dengan menambahkan vokal yang sesuai. Perhatikan perbedaannya karena bisa mengubah makna kata!',
    cards: [
      { char: 'ああ', romaji: 'aa', englishComparison: 'vokal "a" yang dipanjangkan' },
      { char: 'えい', romaji: 'ei', englishComparison: 'seperti "ay" dalam "say"' },
      { char: 'おう', romaji: 'ou', englishComparison: 'seperti "oh" yang dipanjangkan' },
    ],
    closingText: 'おかあさん (okaasan - ibu) vs おかさん (bukan kata) — panjang vokal sangat penting!',
  },
];
