import type { TipCategory, TipDetail } from '@/types/letters';

export const KATAKANA_TIP_CATEGORIES: TipCategory[] = [
  {
    label: 'KATAKANA',
    items: [
      { slug: 'katakana-i-ka-a-sa', characters: 'イ、カ、ア、サ', romaji: 'i, ka, a, sa' },
      { slug: 'katakana-ko-su-shi-u', characters: 'コ、ス、シ、ウ', romaji: 'ko, su, shi, u' },
      { slug: 'katakana-chi-wa-e-mi', characters: 'チ、ワ、エ、ミ', romaji: 'chi, wa, e, mi' },
      { slug: 'katakana-ta-ki-n-o', characters: 'タ、キ、ン、オ', romaji: 'ta, ki, n, o' },
      { slug: 'katakana-ri-ra-tsu-yu', characters: 'リ、ラ、ツ、ユ', romaji: 'ri, ra, tsu, yu' },
      { slug: 'katakana-te-ha-so-ma', characters: 'テ、ハ、ソ、マ', romaji: 'te, ha, so, ma' },
      { slug: 'katakana-ku-mo-se-na', characters: 'ク、モ、セ、ナ', romaji: 'ku, mo, se, na' },
      { slug: 'katakana-fu-ke-ne-ni', characters: 'フ、ケ、ネ、ニ', romaji: 'fu, ke, ne, ni' },
      { slug: 'katakana-ru-nu-hi-ho', characters: 'ル、ヌ、ヒ、ホ', romaji: 'ru, nu, hi, ho' },
      { slug: 'katakana-mu-no-he-ya-re', characters: 'ム、ノ、ヘ、ヤ、レ', romaji: 'mu, no, he, ya, re' },
    ],
  },
  {
    label: 'DAKUTEN',
    items: [
      { slug: 'katakana-ga-gi-gu-ge-go', characters: 'ガ、ギ、グ、ゲ、ゴ', romaji: 'ga, gi, gu, ge, go' },
      { slug: 'katakana-za-zu-ze-zo-ji', characters: 'ザ、ズ、ゼ、ゾ、ジ', romaji: 'za, zu, ze, zo, ji' },
      { slug: 'katakana-da-de-do-ji-zu', characters: 'ダ、デ、ド、ヂ、ヅ', romaji: 'da, de, do, ji, zu' },
      { slug: 'katakana-ba-bi-bu-be-bo', characters: 'バ、ビ、ブ、ベ、ボ', romaji: 'ba, bi, bu, be, bo' },
      { slug: 'katakana-pa-pi-pu-pe-po', characters: 'パ、ピ、プ、ペ、ポ', romaji: 'pa, pi, pu, pe, po' },
    ],
  },
  {
    label: 'KANA KECIL',
    items: [
      { slug: 'katakana-hya-combo', characters: 'ヒャ、ミャ、リャ、キャ、ニャ、シャ、チャ', romaji: 'hya, mya, rya, kya, nya, sha, cha' },
      { slug: 'katakana-yu-combo', characters: 'リュ、キュ、シュ、チュ、ニュ、ヒュ、ミュ', romaji: 'ryu, kyu, shu, chu, nyu, hyu, myu' },
      { slug: 'katakana-yo-combo', characters: 'キョ、ニョ、ヒョ、ミョ、リョ、ショ、チョ', romaji: 'kyo, nyo, hyo, myo, ryo, sho, cho' },
    ],
  },
  {
    label: 'EJAAN',
    items: [
      { slug: 'katakana-small-tsu-1', characters: 'ッ 1: kk, pp, ss, tt', romaji: 'kk, pp, ss, tt' },
      { slug: 'katakana-small-tsu-2', characters: 'ッ 2: ss, kk, pp, tt', romaji: 'ss, kk, pp, tt' },
      { slug: 'katakana-small-tsu-3', characters: 'ッ 3: pp, tt, kk, ss', romaji: 'pp, tt, kk, ss' },
      { slug: 'katakana-small-tsu-4', characters: 'ッ 4: kk, pp, cch, ttsu', romaji: 'kk, pp, cch, ttsu' },
      { slug: 'katakana-long-vowels', characters: 'Vokal panjang: aa, ii, uu, oo, ee', romaji: 'aa, ii, uu, oo, ee' },
    ],
  },
];

export const KATAKANA_TIP_DETAILS: TipDetail[] = [
  {
    slug: 'katakana-hya-combo',
    title: 'Katakana 201',
    explanation: 'Kamu bisa menambahkan ャ kecil untuk mengubah bunyi huruf sebelumnya. Ini membentuk satu suku kata — bukan dua!',
    cards: [
      { char: 'シャ', romaji: 'sha', englishComparison: 'seperti "sha" dalam "shop"' },
      { char: 'チャ', romaji: 'cha', englishComparison: 'seperti "cha" dalam "chop"' },
      { char: 'ニャ', romaji: 'nya', englishComparison: 'seperti "nya" dalam "lanyard"' },
      { char: 'キャ', romaji: 'kya', englishComparison: 'seperti "kya" dalam "backyard"' },
    ],
    closingText: 'Untuk melatih bunyi-bunyi ini, bayangkan menambahkan huruf pertama ke kata seperti "yard". キャ dengan ャ kecil diucapkan kya — satu suku kata! Berbeda dengan キヤ dengan ヤ besar yang diucapkan ki-ya — dua suku kata.',
  },
  {
    slug: 'katakana-yu-combo',
    title: 'Katakana: Combo ュ',
    explanation: 'ュ kecil digabungkan dengan konsonan untuk membentuk suku kata "yu".',
    cards: [
      { char: 'リュ', romaji: 'ryu', englishComparison: 'seperti "ryu" dalam "ryuuichi"' },
      { char: 'キュ', romaji: 'kyu', englishComparison: 'seperti "cu" dalam "cute"' },
      { char: 'シュ', romaji: 'shu', englishComparison: 'seperti "shu" dalam "shoe"' },
      { char: 'チュ', romaji: 'chu', englishComparison: 'seperti "chu" dalam "choose"' },
    ],
  },
  {
    slug: 'katakana-yo-combo',
    title: 'Katakana: Combo ョ',
    explanation: 'ョ kecil digabungkan dengan konsonan untuk membentuk suku kata "yo".',
    cards: [
      { char: 'キョ', romaji: 'kyo', englishComparison: 'seperti "kyo" dalam "Tokyo"' },
      { char: 'ショ', romaji: 'sho', englishComparison: 'seperti "sho" dalam "show"' },
      { char: 'チョ', romaji: 'cho', englishComparison: 'seperti "cho" dalam "chocolate"' },
      { char: 'ニョ', romaji: 'nyo', englishComparison: 'seperti "nyo" dalam bahasa Italia' },
    ],
  },
  {
    slug: 'katakana-small-tsu-1',
    title: 'ッ Kecil 1 — kk, pp, ss, tt',
    explanation: 'ッ kecil menggandakan konsonan yang mengikutinya. Ini menciptakan jedaan singkat yang disengaja sebelum konsonan.',
    cards: [
      { char: 'バッグ', romaji: 'baggu', englishComparison: 'tas (bag)' },
      { char: 'カップ', romaji: 'kappu', englishComparison: 'cangkir (cup)' },
      { char: 'クラッシュ', romaji: 'kurasshu', englishComparison: 'tabrakan (crash)' },
      { char: 'ベッド', romaji: 'beddo', englishComparison: 'tempat tidur (bed)' },
    ],
    closingText: 'Dalam kata serapan bahasa Inggris, ッ sering muncul karena bahasa Inggris memiliki banyak konsonan ganda dan bunyi yang dipotong.',
  },
  {
    slug: 'katakana-long-vowels',
    title: 'Vokal Panjang Katakana',
    explanation: 'Dalam katakana, vokal panjang ditandai dengan garis panjang ー (chōonpu). Ini berbeda dengan hiragana yang menggunakan vokal tambahan.',
    cards: [
      { char: 'コーヒー', romaji: 'koohii', englishComparison: 'kopi (coffee)' },
      { char: 'ケーキ', romaji: 'keeki', englishComparison: 'kue (cake)' },
      { char: 'プール', romaji: 'puuru', englishComparison: 'kolam renang (pool)' },
      { char: 'ビール', romaji: 'biiru', englishComparison: 'bir (beer)' },
    ],
    closingText: 'ー selalu memperpanjang vokal dari karakter sebelumnya. Sangat umum dalam kata serapan bahasa asing!',
  },
  {
    slug: 'katakana-i-ka-a-sa',
    title: 'Katakana: イ、カ、ア、サ',
    explanation: 'Kelompok pertama katakana yang perlu kamu pelajari. Perhatikan kemiripan dan perbedaannya dengan hiragana.',
    cards: [
      { char: 'イ', romaji: 'i', englishComparison: 'seperti "i" dalam "Italian"' },
      { char: 'カ', romaji: 'ka', englishComparison: 'seperti "ka" dalam "karate"' },
      { char: 'ア', romaji: 'a', englishComparison: 'seperti "a" dalam "Asia"' },
      { char: 'サ', romaji: 'sa', englishComparison: 'seperti "sa" dalam "safari"' },
    ],
  },
  {
    slug: 'katakana-ko-su-shi-u',
    title: 'Katakana: コ、ス、シ、ウ',
    explanation: 'Empat huruf katakana dasar yang sering muncul dalam kata serapan bahasa asing. Perhatikan bentuknya yang kaku dan tegas dibanding hiragana.',
    cards: [
      { char: 'コ', romaji: 'ko', englishComparison: 'seperti "co" dalam "coffee"' },
      { char: 'ス', romaji: 'su', englishComparison: 'seperti "su" dalam "super"' },
      { char: 'シ', romaji: 'shi', englishComparison: 'seperti "shi" dalam "sheep"' },
      { char: 'ウ', romaji: 'u', englishComparison: 'seperti "u" dalam "ugh"' },
    ],
    closingText: 'Contoh kata serapan: コーヒー (koohii = kopi), スポーツ (supootsu = olahraga), シャツ (shatsu = kemeja), ウイルス (uirusu = virus).',
  },
  {
    slug: 'katakana-chi-wa-e-mi',
    title: 'Katakana: チ、ワ、エ、ミ',
    explanation: 'Kelompok huruf katakana yang bentuknya cukup unik. チ dan ワ sering membingungkan pemula — perhatikan perbedaannya dengan seksama.',
    cards: [
      { char: 'チ', romaji: 'chi', englishComparison: 'seperti "chi" dalam "cheese"' },
      { char: 'ワ', romaji: 'wa', englishComparison: 'seperti "wa" dalam "water"' },
      { char: 'エ', romaji: 'e', englishComparison: 'seperti "e" dalam "egg"' },
      { char: 'ミ', romaji: 'mi', englishComparison: 'seperti "mi" dalam "me" (bahasa Inggris)' },
    ],
    closingText: 'Kata serapan contoh: チョコレート (chokoreeto = cokelat), ワイン (wain = anggur), エレベーター (erebeetaa = lift), ミルク (miruku = susu).',
  },
  {
    slug: 'katakana-ta-ki-n-o',
    title: 'Katakana: タ、キ、ン、オ',
    explanation: 'Huruf-huruf ini sering muncul dalam kata serapan sehari-hari. ン adalah satu-satunya katakana yang berdiri sendiri sebagai konsonan tanpa vokal.',
    cards: [
      { char: 'タ', romaji: 'ta', englishComparison: 'seperti "ta" dalam "taxi"' },
      { char: 'キ', romaji: 'ki', englishComparison: 'seperti "ki" dalam "key"' },
      { char: 'ン', romaji: 'n', englishComparison: 'seperti "n" dalam "pan"' },
      { char: 'オ', romaji: 'o', englishComparison: 'seperti "o" dalam "orange"' },
    ],
    closingText: 'Contoh: タクシー (takushii = taksi), キロ (kiro = kilo), パン (pan = roti), オレンジ (orenji = jeruk).',
  },
  {
    slug: 'katakana-ri-ra-tsu-yu',
    title: 'Katakana: リ、ラ、ツ、ユ',
    explanation: 'Kelompok ini sering ditemukan dalam nama-nama asing dan kata serapan. ツ terkenal karena wajah emotikon 「ツ」yang ceria!',
    cards: [
      { char: 'リ', romaji: 'ri', englishComparison: 'seperti "ri" dalam "remix"' },
      { char: 'ラ', romaji: 'ra', englishComparison: 'seperti "ra" dalam "radio"' },
      { char: 'ツ', romaji: 'tsu', englishComparison: 'seperti "tsu" dalam "tsunami"' },
      { char: 'ユ', romaji: 'yu', englishComparison: 'seperti "yu" dalam "you"' },
    ],
    closingText: 'Contoh kata serapan: リモコン (rimokon = remote control), ラジオ (rajio = radio), ツアー (tsuaa = tur), ユニフォーム (yunifoomu = seragam).',
  },
  {
    slug: 'katakana-te-ha-so-ma',
    title: 'Katakana: テ、ハ、ソ、マ',
    explanation: 'Empat huruf katakana yang sering muncul dalam kata serapan teknologi dan kehidupan sehari-hari. テ dan ハ mudah diingat dengan latihan rutin.',
    cards: [
      { char: 'テ', romaji: 'te', englishComparison: 'seperti "te" dalam "television"' },
      { char: 'ハ', romaji: 'ha', englishComparison: 'seperti "ha" dalam "ham"' },
      { char: 'ソ', romaji: 'so', englishComparison: 'seperti "so" dalam "sofa"' },
      { char: 'マ', romaji: 'ma', englishComparison: 'seperti "ma" dalam "map"' },
    ],
    closingText: 'Contoh: テレビ (terebi = televisi), ハム (hamu = ham), ソファ (sofa = sofa), マップ (mappu = peta).',
  },
  {
    slug: 'katakana-ku-mo-se-na',
    title: 'Katakana: ク、モ、セ、ナ',
    explanation: 'Kelompok huruf ini sering muncul dalam nama merek dan kata serapan. ク sering digunakan dalam kata teknologi dan makanan.',
    cards: [
      { char: 'ク', romaji: 'ku', englishComparison: 'seperti "ku" dalam "cool"' },
      { char: 'モ', romaji: 'mo', englishComparison: 'seperti "mo" dalam "model"' },
      { char: 'セ', romaji: 'se', englishComparison: 'seperti "se" dalam "set"' },
      { char: 'ナ', romaji: 'na', englishComparison: 'seperti "na" dalam "knife"' },
    ],
    closingText: 'Contoh kata serapan: クラス (kurasu = kelas), モデル (moderu = model), セーター (seetaa = sweater), ナイフ (naifu = pisau).',
  },
  {
    slug: 'katakana-fu-ke-ne-ni',
    title: 'Katakana: フ、ケ、ネ、ニ',
    explanation: 'Huruf-huruf ini sering ditemukan dalam nama negara, makanan, dan produk asing. フ diucapkan seperti "fu" dengan hembusan napas ringan.',
    cards: [
      { char: 'フ', romaji: 'fu', englishComparison: 'seperti "fu" — hembusan napas ringan' },
      { char: 'ケ', romaji: 'ke', englishComparison: 'seperti "ke" dalam "cake"' },
      { char: 'ネ', romaji: 'ne', englishComparison: 'seperti "ne" dalam "neck"' },
      { char: 'ニ', romaji: 'ni', englishComparison: 'seperti "ni" dalam "need"' },
    ],
    closingText: 'Contoh: フランス (furansu = Prancis), ケーキ (keeki = kue), ネクタイ (nekutai = dasi), ニュース (nyuusu = berita).',
  },
  {
    slug: 'katakana-ru-nu-hi-ho',
    title: 'Katakana: ル、ヌ、ヒ、ホ',
    explanation: 'Kelompok ini melengkapi huruf-huruf katakana dasar. ル sangat sering muncul di akhir kata serapan dari bahasa Inggris.',
    cards: [
      { char: 'ル', romaji: 'ru', englishComparison: 'seperti "ru" dalam "rule"' },
      { char: 'ヌ', romaji: 'nu', englishComparison: 'seperti "nu" dalam "noodle"' },
      { char: 'ヒ', romaji: 'hi', englishComparison: 'seperti "hi" dalam "heater"' },
      { char: 'ホ', romaji: 'ho', englishComparison: 'seperti "ho" dalam "hotel"' },
    ],
    closingText: 'Contoh: ルール (ruuru = aturan), ヌードル (nuudoru = mi/noodle), ヒーター (hiitaa = pemanas), ホテル (hoteru = hotel).',
  },
  {
    slug: 'katakana-mu-no-he-ya-re',
    title: 'Katakana: ム、ノ、ヘ、ヤ、レ',
    explanation: 'Lima huruf terakhir kelompok dasar katakana. Setelah menguasai ini, kamu sudah mengenal semua huruf dasar katakana!',
    cards: [
      { char: 'ム', romaji: 'mu', englishComparison: 'seperti "mu" dalam "mood"' },
      { char: 'ノ', romaji: 'no', englishComparison: 'seperti "no" dalam "notebook"' },
      { char: 'ヘ', romaji: 'he', englishComparison: 'seperti "he" dalam "helmet"' },
      { char: 'ヤ', romaji: 'ya', englishComparison: 'seperti "ya" dalam "yard"' },
      { char: 'レ', romaji: 're', englishComparison: 'seperti "re" dalam "restaurant"' },
    ],
    closingText: 'Contoh: ムード (muudo = suasana), ノート (nooto = buku catatan), ヘルメット (herumetto = helm), ヤシ (yashi = kelapa), レストラン (resutoran = restoran).',
  },
  {
    slug: 'katakana-ga-gi-gu-ge-go',
    title: 'Dakuten: ガ、ギ、グ、ゲ、ゴ',
    explanation: 'Tanda dakuten (゛) ditambahkan di sudut kanan atas huruf ka-baris untuk mengubah bunyi "k" menjadi "g". Ini adalah pola yang sama seperti di hiragana.',
    cards: [
      { char: 'ガ', romaji: 'ga', englishComparison: 'seperti "ga" dalam "gas"' },
      { char: 'ギ', romaji: 'gi', englishComparison: 'seperti "gi" dalam "guitar"' },
      { char: 'グ', romaji: 'gu', englishComparison: 'seperti "gu" dalam "good"' },
      { char: 'ゲ', romaji: 'ge', englishComparison: 'seperti "ge" dalam "game"' },
      { char: 'ゴ', romaji: 'go', englishComparison: 'seperti "go" dalam "goal"' },
    ],
    closingText: 'Contoh kata serapan: ガス (gasu = gas), ギター (gitaa = gitar), グラス (gurasu = gelas), ゲーム (geemu = permainan), ゴール (gooru = gol).',
  },
  {
    slug: 'katakana-za-zu-ze-zo-ji',
    title: 'Dakuten: ザ、ズ、ゼ、ゾ、ジ',
    explanation: 'Tanda dakuten pada huruf sa-baris mengubah bunyi "s" menjadi "z". ジ (ji) adalah pengecualian — berasal dari シ (shi) bukan dari ズ.',
    cards: [
      { char: 'ザ', romaji: 'za', englishComparison: 'seperti "za" dalam "pizza"' },
      { char: 'ジ', romaji: 'ji', englishComparison: 'seperti "ji" dalam "jeans"' },
      { char: 'ズ', romaji: 'zu', englishComparison: 'seperti "zu" dalam "zoom"' },
      { char: 'ゼ', romaji: 'ze', englishComparison: 'seperti "ze" dalam "zero"' },
      { char: 'ゾ', romaji: 'zo', englishComparison: 'seperti "zo" dalam "zone"' },
    ],
    closingText: 'Contoh: ザラザラ (zarazara = kasar), ジュース (juusu = jus), ズボン (zubon = celana), ゼロ (zero = nol), ゾーン (zoon = zona).',
  },
  {
    slug: 'katakana-da-de-do-ji-zu',
    title: 'Dakuten: ダ、デ、ド、ヂ、ヅ',
    explanation: 'Tanda dakuten pada huruf ta-baris mengubah bunyi "t" menjadi "d". ヂ dan ヅ sangat jarang digunakan — dalam praktiknya ジ dan ズ lebih umum.',
    cards: [
      { char: 'ダ', romaji: 'da', englishComparison: 'seperti "da" dalam "dance"' },
      { char: 'デ', romaji: 'de', englishComparison: 'seperti "de" dalam "date"' },
      { char: 'ド', romaji: 'do', englishComparison: 'seperti "do" dalam "door"' },
      { char: 'ヂ', romaji: 'ji', englishComparison: 'sama dengan ジ (ji), tapi sangat jarang' },
      { char: 'ヅ', romaji: 'zu', englishComparison: 'sama dengan ズ (zu), tapi sangat jarang' },
    ],
    closingText: 'Contoh umum: ダンス (dansu = tarian), デート (deeto = kencan), ドア (doa = pintu). ヂ dan ヅ hampir tidak pernah dipakai dalam kata serapan modern.',
  },
  {
    slug: 'katakana-ba-bi-bu-be-bo',
    title: 'Dakuten: バ、ビ、ブ、ベ、ボ',
    explanation: 'Tanda dakuten pada huruf ha-baris mengubah bunyi "h" menjadi "b". Kelompok ini sangat umum dalam kata serapan bahasa Inggris.',
    cards: [
      { char: 'バ', romaji: 'ba', englishComparison: 'seperti "ba" dalam "bus"' },
      { char: 'ビ', romaji: 'bi', englishComparison: 'seperti "bi" dalam "beer"' },
      { char: 'ブ', romaji: 'bu', englishComparison: 'seperti "bu" dalam "boot"' },
      { char: 'ベ', romaji: 'be', englishComparison: 'seperti "be" dalam "bed"' },
      { char: 'ボ', romaji: 'bo', englishComparison: 'seperti "bo" dalam "ball"' },
    ],
    closingText: 'Contoh: バス (basu = bus), ビール (biiru = bir), ブーツ (buutsu = sepatu bot), ベッド (beddo = tempat tidur), ボール (booru = bola).',
  },
  {
    slug: 'katakana-pa-pi-pu-pe-po',
    title: 'Handakuten: パ、ピ、プ、ペ、ポ',
    explanation: 'Tanda handakuten (゜) — lingkaran kecil — ditambahkan pada huruf ha-baris untuk mengubah bunyi "h/b" menjadi "p". Hanya ha-baris yang memiliki handakuten.',
    cards: [
      { char: 'パ', romaji: 'pa', englishComparison: 'seperti "pa" dalam "pasta"' },
      { char: 'ピ', romaji: 'pi', englishComparison: 'seperti "pi" dalam "piano"' },
      { char: 'プ', romaji: 'pu', englishComparison: 'seperti "pu" dalam "pool"' },
      { char: 'ペ', romaji: 'pe', englishComparison: 'seperti "pe" dalam "pen"' },
      { char: 'ポ', romaji: 'po', englishComparison: 'seperti "po" dalam "poster"' },
    ],
    closingText: 'Contoh: パスタ (pasuta = pasta), ピアノ (piano = piano), プール (puuru = kolam renang), ペン (pen = pena), ポスター (posutaa = poster).',
  },
  {
    slug: 'katakana-small-tsu-2',
    title: 'ッ Kecil 2 — ss, kk, pp, tt',
    explanation: 'Latihan lanjutan ッ kecil dengan urutan konsonan berbeda. ッ menciptakan jedaan singkat yang terdengar seperti konsonan "tertahan" sebelum dilepaskan.',
    cards: [
      { char: 'アッサリ', romaji: 'assari', englishComparison: 'ringan/sederhana' },
      { char: 'バッグ', romaji: 'baggu', englishComparison: 'tas (bag)' },
      { char: 'カップ', romaji: 'kappu', englishComparison: 'cangkir (cup)' },
      { char: 'ベッド', romaji: 'beddo', englishComparison: 'tempat tidur (bed)' },
    ],
    closingText: 'Perhatikan bahwa ッ selalu mengikuti konsonan berikutnya — bukan konsonan sebelumnya. バッグ: bunyi "g" yang digandakan terdengar seperti jeda sebelum "gu".',
  },
  {
    slug: 'katakana-small-tsu-3',
    title: 'ッ Kecil 3 — pp, tt, kk, ss',
    explanation: 'Praktik ッ kecil dengan fokus pada kata serapan dari bahasa Inggris. Banyak kata Inggris yang berakhir konsonan diadaptasi dengan ッ di katakana.',
    cards: [
      { char: 'カップ', romaji: 'kappu', englishComparison: 'cangkir (cup)' },
      { char: 'ベッド', romaji: 'beddo', englishComparison: 'tempat tidur (bed)' },
      { char: 'バッグ', romaji: 'baggu', englishComparison: 'tas (bag)' },
      { char: 'クラッシュ', romaji: 'kurasshu', englishComparison: 'tabrakan (crash)' },
    ],
    closingText: 'Dalam bahasa Jepang tidak ada kata yang berakhir konsonan (kecuali ン). Kata Inggris seperti "cup" → カップ (kappu) — huruf "p" akhir diubah menjadi ッ+プ.',
  },
  {
    slug: 'katakana-small-tsu-4',
    title: 'ッ Kecil 4 — kk, pp, cch, ttsu',
    explanation: 'Variasi lanjutan ッ termasuk kombinasi "cch" dan "ttsu" yang lebih jarang. Pola ini muncul dalam kata serapan dengan bunyi konsonan yang lebih kompleks.',
    cards: [
      { char: 'バッグ', romaji: 'baggu', englishComparison: 'tas (bag)' },
      { char: 'カップ', romaji: 'kappu', englishComparison: 'cangkir (cup)' },
      { char: 'マッチ', romaji: 'macchi', englishComparison: 'korek api (match)' },
      { char: 'ピッツァ', romaji: 'pittsa', englishComparison: 'pizza' },
    ],
    closingText: 'Kombinasi マッチ (macchi) dan ピッツァ (pittsa) menunjukkan bagaimana ッ dipakai untuk bunyi "tch" dan "tz" yang tidak ada dalam sistem suku kata Jepang biasa.',
  },
];
