/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LettersIndexRouteImport } from './routes/letters/index'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as QuizzesSlugRouteImport } from './routes/quizzes/$slug'
import { Route as LearningLevelRouteImport } from './routes/learning/$level'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiAchievementsRouteImport } from './routes/api/achievements'
import { Route as LearningLevelIndexRouteImport } from './routes/learning/$level.index'
import { Route as ApiQuizBankIndexRouteImport } from './routes/api/quiz-bank/index'
import { Route as LettersTipsTypeRouteImport } from './routes/letters/tips.$type'
import { Route as LearningLevelStepSlugRouteImport } from './routes/learning/$level.$stepSlug'
import { Route as ApiQuizSubmitRouteImport } from './routes/api/quiz/submit'
import { Route as ApiQuizBankSlugRouteImport } from './routes/api/quiz-bank/$slug'
import { Route as ApiProgressCompleteRouteImport } from './routes/api/progress/complete'
import { Route as ApiProgressLevelRouteImport } from './routes/api/progress/$level'
import { Route as ApiAuthVerifyOtpRouteImport } from './routes/api/auth/verify-otp'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthSendOtpRouteImport } from './routes/api/auth/send-otp'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAssessmentSubmitRouteImport } from './routes/api/assessment/submit'
import { Route as LettersTipsTypeIndexRouteImport } from './routes/letters/tips.$type.index'
import { Route as LettersTipsTypeTipSlugRouteImport } from './routes/letters/tips.$type.$tipSlug'
import { Route as ApiQuizSlugHistoryRouteImport } from './routes/api/quiz/$slug/history'
import { Route as ApiLearningLevelProgressRouteImport } from './routes/api/learning/$level/progress'
import { Route as LearningLevelUnitSectionSlugUnitSlugRouteImport } from './routes/learning/$level.unit.$sectionSlug.$unitSlug'
import { Route as LearningLevelGuidebookSectionSlugUnitSlugRouteImport } from './routes/learning/$level.guidebook.$sectionSlug.$unitSlug'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIndexRoute = LettersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LettersRoute,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesSlugRoute = QuizzesSlugRouteImport.update({
  id: '/quizzes/$slug',
  path: '/quizzes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningLevelRoute = LearningLevelRouteImport.update({
  id: '/learning/$level',
  path: '/learning/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAchievementsRoute = ApiAchievementsRouteImport.update({
  id: '/api/achievements',
  path: '/api/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningLevelIndexRoute = LearningLevelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearningLevelRoute,
} as any)
const ApiQuizBankIndexRoute = ApiQuizBankIndexRouteImport.update({
  id: '/api/quiz-bank/',
  path: '/api/quiz-bank/',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersTipsTypeRoute = LettersTipsTypeRouteImport.update({
  id: '/tips/$type',
  path: '/tips/$type',
  getParentRoute: () => LettersRoute,
} as any)
const LearningLevelStepSlugRoute = LearningLevelStepSlugRouteImport.update({
  id: '/$stepSlug',
  path: '/$stepSlug',
  getParentRoute: () => LearningLevelRoute,
} as any)
const ApiQuizSubmitRoute = ApiQuizSubmitRouteImport.update({
  id: '/api/quiz/submit',
  path: '/api/quiz/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizBankSlugRoute = ApiQuizBankSlugRouteImport.update({
  id: '/api/quiz-bank/$slug',
  path: '/api/quiz-bank/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressCompleteRoute = ApiProgressCompleteRouteImport.update({
  id: '/api/progress/complete',
  path: '/api/progress/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProgressLevelRoute = ApiProgressLevelRouteImport.update({
  id: '/api/progress/$level',
  path: '/api/progress/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyOtpRoute = ApiAuthVerifyOtpRouteImport.update({
  id: '/api/auth/verify-otp',
  path: '/api/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendOtpRoute = ApiAuthSendOtpRouteImport.update({
  id: '/api/auth/send-otp',
  path: '/api/auth/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentSubmitRoute = ApiAssessmentSubmitRouteImport.update({
  id: '/api/assessment/submit',
  path: '/api/assessment/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersTipsTypeIndexRoute = LettersTipsTypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LettersTipsTypeRoute,
} as any)
const LettersTipsTypeTipSlugRoute = LettersTipsTypeTipSlugRouteImport.update({
  id: '/$tipSlug',
  path: '/$tipSlug',
  getParentRoute: () => LettersTipsTypeRoute,
} as any)
const ApiQuizSlugHistoryRoute = ApiQuizSlugHistoryRouteImport.update({
  id: '/api/quiz/$slug/history',
  path: '/api/quiz/$slug/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningLevelProgressRoute =
  ApiLearningLevelProgressRouteImport.update({
    id: '/api/learning/$level/progress',
    path: '/api/learning/$level/progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningLevelUnitSectionSlugUnitSlugRoute =
  LearningLevelUnitSectionSlugUnitSlugRouteImport.update({
    id: '/unit/$sectionSlug/$unitSlug',
    path: '/unit/$sectionSlug/$unitSlug',
    getParentRoute: () => LearningLevelRoute,
  } as any)
const LearningLevelGuidebookSectionSlugUnitSlugRoute =
  LearningLevelGuidebookSectionSlugUnitSlugRouteImport.update({
    id: '/guidebook/$sectionSlug/$unitSlug',
    path: '/guidebook/$sectionSlug/$unitSlug',
    getParentRoute: () => LearningLevelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/letters': typeof LettersRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/achievements': typeof ApiAchievementsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/learning/$level': typeof LearningLevelRouteWithChildren
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/learning/': typeof LearningIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/api/assessment/submit': typeof ApiAssessmentSubmitRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/progress/$level': typeof ApiProgressLevelRoute
  '/api/progress/complete': typeof ApiProgressCompleteRoute
  '/api/quiz-bank/$slug': typeof ApiQuizBankSlugRoute
  '/api/quiz/submit': typeof ApiQuizSubmitRoute
  '/learning/$level/$stepSlug': typeof LearningLevelStepSlugRoute
  '/letters/tips/$type': typeof LettersTipsTypeRouteWithChildren
  '/api/quiz-bank/': typeof ApiQuizBankIndexRoute
  '/learning/$level/': typeof LearningLevelIndexRoute
  '/api/learning/$level/progress': typeof ApiLearningLevelProgressRoute
  '/api/quiz/$slug/history': typeof ApiQuizSlugHistoryRoute
  '/letters/tips/$type/$tipSlug': typeof LettersTipsTypeTipSlugRoute
  '/letters/tips/$type/': typeof LettersTipsTypeIndexRoute
  '/learning/$level/guidebook/$sectionSlug/$unitSlug': typeof LearningLevelGuidebookSectionSlugUnitSlugRoute
  '/learning/$level/unit/$sectionSlug/$unitSlug': typeof LearningLevelUnitSectionSlugUnitSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/achievements': typeof ApiAchievementsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/learning': typeof LearningIndexRoute
  '/letters': typeof LettersIndexRoute
  '/api/assessment/submit': typeof ApiAssessmentSubmitRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/progress/$level': typeof ApiProgressLevelRoute
  '/api/progress/complete': typeof ApiProgressCompleteRoute
  '/api/quiz-bank/$slug': typeof ApiQuizBankSlugRoute
  '/api/quiz/submit': typeof ApiQuizSubmitRoute
  '/learning/$level/$stepSlug': typeof LearningLevelStepSlugRoute
  '/api/quiz-bank': typeof ApiQuizBankIndexRoute
  '/learning/$level': typeof LearningLevelIndexRoute
  '/api/learning/$level/progress': typeof ApiLearningLevelProgressRoute
  '/api/quiz/$slug/history': typeof ApiQuizSlugHistoryRoute
  '/letters/tips/$type/$tipSlug': typeof LettersTipsTypeTipSlugRoute
  '/letters/tips/$type': typeof LettersTipsTypeIndexRoute
  '/learning/$level/guidebook/$sectionSlug/$unitSlug': typeof LearningLevelGuidebookSectionSlugUnitSlugRoute
  '/learning/$level/unit/$sectionSlug/$unitSlug': typeof LearningLevelUnitSectionSlugUnitSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/letters': typeof LettersRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/api/achievements': typeof ApiAchievementsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/learning/$level': typeof LearningLevelRouteWithChildren
  '/quizzes/$slug': typeof QuizzesSlugRoute
  '/learning/': typeof LearningIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/api/assessment/submit': typeof ApiAssessmentSubmitRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/api/progress/$level': typeof ApiProgressLevelRoute
  '/api/progress/complete': typeof ApiProgressCompleteRoute
  '/api/quiz-bank/$slug': typeof ApiQuizBankSlugRoute
  '/api/quiz/submit': typeof ApiQuizSubmitRoute
  '/learning/$level/$stepSlug': typeof LearningLevelStepSlugRoute
  '/letters/tips/$type': typeof LettersTipsTypeRouteWithChildren
  '/api/quiz-bank/': typeof ApiQuizBankIndexRoute
  '/learning/$level/': typeof LearningLevelIndexRoute
  '/api/learning/$level/progress': typeof ApiLearningLevelProgressRoute
  '/api/quiz/$slug/history': typeof ApiQuizSlugHistoryRoute
  '/letters/tips/$type/$tipSlug': typeof LettersTipsTypeTipSlugRoute
  '/letters/tips/$type/': typeof LettersTipsTypeIndexRoute
  '/learning/$level/guidebook/$sectionSlug/$unitSlug': typeof LearningLevelGuidebookSectionSlugUnitSlugRoute
  '/learning/$level/unit/$sectionSlug/$unitSlug': typeof LearningLevelUnitSectionSlugUnitSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/letters'
    | '/onboarding'
    | '/profile'
    | '/api/achievements'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/learning/$level'
    | '/quizzes/$slug'
    | '/learning/'
    | '/letters/'
    | '/api/assessment/submit'
    | '/api/auth/logout'
    | '/api/auth/send-otp'
    | '/api/auth/session'
    | '/api/auth/verify-otp'
    | '/api/progress/$level'
    | '/api/progress/complete'
    | '/api/quiz-bank/$slug'
    | '/api/quiz/submit'
    | '/learning/$level/$stepSlug'
    | '/letters/tips/$type'
    | '/api/quiz-bank/'
    | '/learning/$level/'
    | '/api/learning/$level/progress'
    | '/api/quiz/$slug/history'
    | '/letters/tips/$type/$tipSlug'
    | '/letters/tips/$type/'
    | '/learning/$level/guidebook/$sectionSlug/$unitSlug'
    | '/learning/$level/unit/$sectionSlug/$unitSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/profile'
    | '/api/achievements'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/quizzes/$slug'
    | '/learning'
    | '/letters'
    | '/api/assessment/submit'
    | '/api/auth/logout'
    | '/api/auth/send-otp'
    | '/api/auth/session'
    | '/api/auth/verify-otp'
    | '/api/progress/$level'
    | '/api/progress/complete'
    | '/api/quiz-bank/$slug'
    | '/api/quiz/submit'
    | '/learning/$level/$stepSlug'
    | '/api/quiz-bank'
    | '/learning/$level'
    | '/api/learning/$level/progress'
    | '/api/quiz/$slug/history'
    | '/letters/tips/$type/$tipSlug'
    | '/letters/tips/$type'
    | '/learning/$level/guidebook/$sectionSlug/$unitSlug'
    | '/learning/$level/unit/$sectionSlug/$unitSlug'
  id:
    | '__root__'
    | '/'
    | '/letters'
    | '/onboarding'
    | '/profile'
    | '/api/achievements'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-otp'
    | '/learning/$level'
    | '/quizzes/$slug'
    | '/learning/'
    | '/letters/'
    | '/api/assessment/submit'
    | '/api/auth/logout'
    | '/api/auth/send-otp'
    | '/api/auth/session'
    | '/api/auth/verify-otp'
    | '/api/progress/$level'
    | '/api/progress/complete'
    | '/api/quiz-bank/$slug'
    | '/api/quiz/submit'
    | '/learning/$level/$stepSlug'
    | '/letters/tips/$type'
    | '/api/quiz-bank/'
    | '/learning/$level/'
    | '/api/learning/$level/progress'
    | '/api/quiz/$slug/history'
    | '/letters/tips/$type/$tipSlug'
    | '/letters/tips/$type/'
    | '/learning/$level/guidebook/$sectionSlug/$unitSlug'
    | '/learning/$level/unit/$sectionSlug/$unitSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LettersRoute: typeof LettersRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ApiAchievementsRoute: typeof ApiAchievementsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  LearningLevelRoute: typeof LearningLevelRouteWithChildren
  QuizzesSlugRoute: typeof QuizzesSlugRoute
  LearningIndexRoute: typeof LearningIndexRoute
  ApiAssessmentSubmitRoute: typeof ApiAssessmentSubmitRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSendOtpRoute: typeof ApiAuthSendOtpRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyOtpRoute: typeof ApiAuthVerifyOtpRoute
  ApiProgressLevelRoute: typeof ApiProgressLevelRoute
  ApiProgressCompleteRoute: typeof ApiProgressCompleteRoute
  ApiQuizBankSlugRoute: typeof ApiQuizBankSlugRoute
  ApiQuizSubmitRoute: typeof ApiQuizSubmitRoute
  ApiQuizBankIndexRoute: typeof ApiQuizBankIndexRoute
  ApiLearningLevelProgressRoute: typeof ApiLearningLevelProgressRoute
  ApiQuizSlugHistoryRoute: typeof ApiQuizSlugHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/': {
      id: '/letters/'
      path: '/'
      fullPath: '/letters/'
      preLoaderRoute: typeof LettersIndexRouteImport
      parentRoute: typeof LettersRoute
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$slug': {
      id: '/quizzes/$slug'
      path: '/quizzes/$slug'
      fullPath: '/quizzes/$slug'
      preLoaderRoute: typeof QuizzesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$level': {
      id: '/learning/$level'
      path: '/learning/$level'
      fullPath: '/learning/$level'
      preLoaderRoute: typeof LearningLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/achievements': {
      id: '/api/achievements'
      path: '/api/achievements'
      fullPath: '/api/achievements'
      preLoaderRoute: typeof ApiAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$level/': {
      id: '/learning/$level/'
      path: '/'
      fullPath: '/learning/$level/'
      preLoaderRoute: typeof LearningLevelIndexRouteImport
      parentRoute: typeof LearningLevelRoute
    }
    '/api/quiz-bank/': {
      id: '/api/quiz-bank/'
      path: '/api/quiz-bank'
      fullPath: '/api/quiz-bank/'
      preLoaderRoute: typeof ApiQuizBankIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/tips/$type': {
      id: '/letters/tips/$type'
      path: '/tips/$type'
      fullPath: '/letters/tips/$type'
      preLoaderRoute: typeof LettersTipsTypeRouteImport
      parentRoute: typeof LettersRoute
    }
    '/learning/$level/$stepSlug': {
      id: '/learning/$level/$stepSlug'
      path: '/$stepSlug'
      fullPath: '/learning/$level/$stepSlug'
      preLoaderRoute: typeof LearningLevelStepSlugRouteImport
      parentRoute: typeof LearningLevelRoute
    }
    '/api/quiz/submit': {
      id: '/api/quiz/submit'
      path: '/api/quiz/submit'
      fullPath: '/api/quiz/submit'
      preLoaderRoute: typeof ApiQuizSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz-bank/$slug': {
      id: '/api/quiz-bank/$slug'
      path: '/api/quiz-bank/$slug'
      fullPath: '/api/quiz-bank/$slug'
      preLoaderRoute: typeof ApiQuizBankSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/complete': {
      id: '/api/progress/complete'
      path: '/api/progress/complete'
      fullPath: '/api/progress/complete'
      preLoaderRoute: typeof ApiProgressCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/progress/$level': {
      id: '/api/progress/$level'
      path: '/api/progress/$level'
      fullPath: '/api/progress/$level'
      preLoaderRoute: typeof ApiProgressLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-otp': {
      id: '/api/auth/verify-otp'
      path: '/api/auth/verify-otp'
      fullPath: '/api/auth/verify-otp'
      preLoaderRoute: typeof ApiAuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-otp': {
      id: '/api/auth/send-otp'
      path: '/api/auth/send-otp'
      fullPath: '/api/auth/send-otp'
      preLoaderRoute: typeof ApiAuthSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment/submit': {
      id: '/api/assessment/submit'
      path: '/api/assessment/submit'
      fullPath: '/api/assessment/submit'
      preLoaderRoute: typeof ApiAssessmentSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/tips/$type/': {
      id: '/letters/tips/$type/'
      path: '/'
      fullPath: '/letters/tips/$type/'
      preLoaderRoute: typeof LettersTipsTypeIndexRouteImport
      parentRoute: typeof LettersTipsTypeRoute
    }
    '/letters/tips/$type/$tipSlug': {
      id: '/letters/tips/$type/$tipSlug'
      path: '/$tipSlug'
      fullPath: '/letters/tips/$type/$tipSlug'
      preLoaderRoute: typeof LettersTipsTypeTipSlugRouteImport
      parentRoute: typeof LettersTipsTypeRoute
    }
    '/api/quiz/$slug/history': {
      id: '/api/quiz/$slug/history'
      path: '/api/quiz/$slug/history'
      fullPath: '/api/quiz/$slug/history'
      preLoaderRoute: typeof ApiQuizSlugHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/$level/progress': {
      id: '/api/learning/$level/progress'
      path: '/api/learning/$level/progress'
      fullPath: '/api/learning/$level/progress'
      preLoaderRoute: typeof ApiLearningLevelProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$level/unit/$sectionSlug/$unitSlug': {
      id: '/learning/$level/unit/$sectionSlug/$unitSlug'
      path: '/unit/$sectionSlug/$unitSlug'
      fullPath: '/learning/$level/unit/$sectionSlug/$unitSlug'
      preLoaderRoute: typeof LearningLevelUnitSectionSlugUnitSlugRouteImport
      parentRoute: typeof LearningLevelRoute
    }
    '/learning/$level/guidebook/$sectionSlug/$unitSlug': {
      id: '/learning/$level/guidebook/$sectionSlug/$unitSlug'
      path: '/guidebook/$sectionSlug/$unitSlug'
      fullPath: '/learning/$level/guidebook/$sectionSlug/$unitSlug'
      preLoaderRoute: typeof LearningLevelGuidebookSectionSlugUnitSlugRouteImport
      parentRoute: typeof LearningLevelRoute
    }
  }
}

interface LettersTipsTypeRouteChildren {
  LettersTipsTypeTipSlugRoute: typeof LettersTipsTypeTipSlugRoute
  LettersTipsTypeIndexRoute: typeof LettersTipsTypeIndexRoute
}

const LettersTipsTypeRouteChildren: LettersTipsTypeRouteChildren = {
  LettersTipsTypeTipSlugRoute: LettersTipsTypeTipSlugRoute,
  LettersTipsTypeIndexRoute: LettersTipsTypeIndexRoute,
}

const LettersTipsTypeRouteWithChildren = LettersTipsTypeRoute._addFileChildren(
  LettersTipsTypeRouteChildren,
)

interface LettersRouteChildren {
  LettersIndexRoute: typeof LettersIndexRoute
  LettersTipsTypeRoute: typeof LettersTipsTypeRouteWithChildren
}

const LettersRouteChildren: LettersRouteChildren = {
  LettersIndexRoute: LettersIndexRoute,
  LettersTipsTypeRoute: LettersTipsTypeRouteWithChildren,
}

const LettersRouteWithChildren =
  LettersRoute._addFileChildren(LettersRouteChildren)

interface LearningLevelRouteChildren {
  LearningLevelStepSlugRoute: typeof LearningLevelStepSlugRoute
  LearningLevelIndexRoute: typeof LearningLevelIndexRoute
  LearningLevelGuidebookSectionSlugUnitSlugRoute: typeof LearningLevelGuidebookSectionSlugUnitSlugRoute
  LearningLevelUnitSectionSlugUnitSlugRoute: typeof LearningLevelUnitSectionSlugUnitSlugRoute
}

const LearningLevelRouteChildren: LearningLevelRouteChildren = {
  LearningLevelStepSlugRoute: LearningLevelStepSlugRoute,
  LearningLevelIndexRoute: LearningLevelIndexRoute,
  LearningLevelGuidebookSectionSlugUnitSlugRoute:
    LearningLevelGuidebookSectionSlugUnitSlugRoute,
  LearningLevelUnitSectionSlugUnitSlugRoute:
    LearningLevelUnitSectionSlugUnitSlugRoute,
}

const LearningLevelRouteWithChildren = LearningLevelRoute._addFileChildren(
  LearningLevelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LettersRoute: LettersRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ApiAchievementsRoute: ApiAchievementsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  LearningLevelRoute: LearningLevelRouteWithChildren,
  QuizzesSlugRoute: QuizzesSlugRoute,
  LearningIndexRoute: LearningIndexRoute,
  ApiAssessmentSubmitRoute: ApiAssessmentSubmitRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSendOtpRoute: ApiAuthSendOtpRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyOtpRoute: ApiAuthVerifyOtpRoute,
  ApiProgressLevelRoute: ApiProgressLevelRoute,
  ApiProgressCompleteRoute: ApiProgressCompleteRoute,
  ApiQuizBankSlugRoute: ApiQuizBankSlugRoute,
  ApiQuizSubmitRoute: ApiQuizSubmitRoute,
  ApiQuizBankIndexRoute: ApiQuizBankIndexRoute,
  ApiLearningLevelProgressRoute: ApiLearningLevelProgressRoute,
  ApiQuizSlugHistoryRoute: ApiQuizSlugHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
